/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

package org.opensearch.indices.pollingingest.mappers;

import org.opensearch.index.IngestionShardPointer;
import org.opensearch.index.Message;
import org.opensearch.index.engine.FakeIngestionSource;
import org.opensearch.indices.pollingingest.ShardUpdateMessage;
import org.opensearch.test.OpenSearchTestCase;

import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import static org.opensearch.action.index.IndexRequest.UNSET_AUTO_GENERATED_TIMESTAMP;

public class FieldMappingIngestionMessageMapperTests extends OpenSearchTestCase {

    private ShardUpdateMessage mapMessage(FieldMappingIngestionMessageMapper mapper, String payload) {
        byte[] payloadBytes = payload.getBytes(StandardCharsets.UTF_8);
        IngestionShardPointer pointer = new FakeIngestionSource.FakeIngestionShardPointer(1);
        Message message = new FakeIngestionSource.FakeIngestionMessage(payloadBytes);
        return mapper.mapAndProcess(pointer, message);
    }

    // --- ID field tests ---

    public void testIdFieldExtraction() {
        Map<String, Object> settings = Map.of(FieldMappingIngestionMessageMapper.ID_FIELD, "user_id");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage result = mapMessage(mapper, "{\"user_id\": \"abc\", \"name\": \"alice\"}");

        Map<String, Object> payloadMap = result.parsedPayloadMap();
        assertEquals("abc", payloadMap.get("_id"));
        assertEquals(UNSET_AUTO_GENERATED_TIMESTAMP, result.autoGeneratedIdTimestamp());

        Map<String, Object> source = (Map<String, Object>) payloadMap.get("_source");
        assertFalse(source.containsKey("user_id"));
        assertEquals("alice", source.get("name"));
    }

    public void testIdFieldMissing_ThrowsException() {
        Map<String, Object> settings = Map.of(FieldMappingIngestionMessageMapper.ID_FIELD, "user_id");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        IllegalArgumentException e = expectThrows(IllegalArgumentException.class, () -> mapMessage(mapper, "{\"name\": \"alice\"}"));
        assertTrue(e.getMessage().contains("configured id_field [user_id] is missing from the message"));
    }

    public void testIdFieldNull_ThrowsException() {
        Map<String, Object> settings = Map.of(FieldMappingIngestionMessageMapper.ID_FIELD, "user_id");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        IllegalArgumentException e = expectThrows(
            IllegalArgumentException.class,
            () -> mapMessage(mapper, "{\"user_id\": null, \"name\": \"alice\"}")
        );
        assertTrue(e.getMessage().contains("field [user_id] has a null value"));
    }

    public void testIdFieldEmptyString_ThrowsException() {
        Map<String, Object> settings = Map.of(FieldMappingIngestionMessageMapper.ID_FIELD, "user_id");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        IllegalArgumentException e = expectThrows(
            IllegalArgumentException.class,
            () -> mapMessage(mapper, "{\"user_id\": \"\", \"name\": \"alice\"}")
        );
        assertTrue(e.getMessage().contains("field [user_id] has an empty value"));
    }

    public void testNoIdFieldConfigured_AutoGenerates() {
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(Collections.emptyMap());

        ShardUpdateMessage result = mapMessage(mapper, "{\"name\": \"alice\"}");

        Map<String, Object> payloadMap = result.parsedPayloadMap();
        assertNotNull(payloadMap.get("_id"));
        assertNotEquals(UNSET_AUTO_GENERATED_TIMESTAMP, result.autoGeneratedIdTimestamp());
    }

    public void testNumericIdField() {
        Map<String, Object> settings = Map.of(FieldMappingIngestionMessageMapper.ID_FIELD, "id");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage result = mapMessage(mapper, "{\"id\": 12345, \"name\": \"alice\"}");

        Map<String, Object> payloadMap = result.parsedPayloadMap();
        assertEquals("12345", payloadMap.get("_id"));
    }

    // --- Version field tests ---

    public void testVersionFieldExtraction() {
        Map<String, Object> settings = Map.of(
            FieldMappingIngestionMessageMapper.ID_FIELD,
            "user_id",
            FieldMappingIngestionMessageMapper.VERSION_FIELD,
            "timestamp"
        );
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage result = mapMessage(mapper, "{\"user_id\": \"abc\", \"timestamp\": 1234567890, \"name\": \"alice\"}");

        Map<String, Object> payloadMap = result.parsedPayloadMap();
        assertEquals("abc", payloadMap.get("_id"));
        assertEquals("1234567890", payloadMap.get("_version"));

        Map<String, Object> source = (Map<String, Object>) payloadMap.get("_source");
        assertFalse(source.containsKey("timestamp"));
        assertEquals("alice", source.get("name"));
    }

    public void testVersionFieldMissing_ThrowsException() {
        Map<String, Object> settings = Map.of(FieldMappingIngestionMessageMapper.VERSION_FIELD, "timestamp");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        IllegalArgumentException e = expectThrows(IllegalArgumentException.class, () -> mapMessage(mapper, "{\"name\": \"alice\"}"));
        assertTrue(e.getMessage().contains("configured version_field [timestamp] is missing from the message"));
    }

    // --- Op type field tests (delete_value) ---

    public void testDeleteValueConfigured_MatchesDelete() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "status");
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "expired");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage result = mapMessage(mapper, "{\"status\": \"expired\", \"name\": \"alice\"}");
        assertEquals("delete", result.parsedPayloadMap().get("_op_type"));
    }

    public void testDeleteValueConfigured_NoMatch_DefaultsToIndex() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "status");
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "expired");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage result = mapMessage(mapper, "{\"status\": \"active\", \"name\": \"alice\"}");
        assertEquals("index", result.parsedPayloadMap().get("_op_type"));
    }

    public void testDeleteValueConfigured_YN() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "is_deleted");
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "Y");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage deleteResult = mapMessage(mapper, "{\"is_deleted\": \"Y\", \"name\": \"alice\"}");
        assertEquals("delete", deleteResult.parsedPayloadMap().get("_op_type"));

        ShardUpdateMessage indexResult = mapMessage(mapper, "{\"is_deleted\": \"N\", \"name\": \"alice\"}");
        assertEquals("index", indexResult.parsedPayloadMap().get("_op_type"));
    }

    public void testDeleteValueConfigured_IntegerValues() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "op");
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "1");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage deleteResult = mapMessage(mapper, "{\"op\": 1, \"name\": \"alice\"}");
        assertEquals("delete", deleteResult.parsedPayloadMap().get("_op_type"));

        ShardUpdateMessage indexResult = mapMessage(mapper, "{\"op\": 0, \"name\": \"alice\"}");
        assertEquals("index", indexResult.parsedPayloadMap().get("_op_type"));
    }

    public void testDeleteValueConfigured_BooleanTrue() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "is_deleted");
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "true");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage deleteResult = mapMessage(mapper, "{\"is_deleted\": true, \"name\": \"alice\"}");
        assertEquals("delete", deleteResult.parsedPayloadMap().get("_op_type"));

        ShardUpdateMessage indexResult = mapMessage(mapper, "{\"is_deleted\": false, \"name\": \"alice\"}");
        assertEquals("index", indexResult.parsedPayloadMap().get("_op_type"));
    }

    // --- Op type field tests (create_value) ---

    public void testCreateValueConfigured() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "action");
        settings.put(FieldMappingIngestionMessageMapper.CREATE_VALUE, "INSERT");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage createResult = mapMessage(mapper, "{\"action\": \"INSERT\", \"name\": \"alice\"}");
        assertEquals("create", createResult.parsedPayloadMap().get("_op_type"));

        ShardUpdateMessage indexResult = mapMessage(mapper, "{\"action\": \"UPDATE\", \"name\": \"alice\"}");
        assertEquals("index", indexResult.parsedPayloadMap().get("_op_type"));
    }

    public void testDeleteAndCreateValueConfigured() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "op");
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "DELETE");
        settings.put(FieldMappingIngestionMessageMapper.CREATE_VALUE, "INSERT");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage deleteResult = mapMessage(mapper, "{\"op\": \"DELETE\", \"name\": \"alice\"}");
        assertEquals("delete", deleteResult.parsedPayloadMap().get("_op_type"));

        ShardUpdateMessage createResult = mapMessage(mapper, "{\"op\": \"INSERT\", \"name\": \"alice\"}");
        assertEquals("create", createResult.parsedPayloadMap().get("_op_type"));

        ShardUpdateMessage indexResult = mapMessage(mapper, "{\"op\": \"UPDATE\", \"name\": \"alice\"}");
        assertEquals("index", indexResult.parsedPayloadMap().get("_op_type"));
    }

    // --- Op type field: no delete_value/create_value = everything is index ---

    public void testOpTypeFieldWithoutValues_DefaultsToIndex() {
        Map<String, Object> settings = Map.of(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "is_deleted");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        // Without delete_value configured, even "true" is index
        ShardUpdateMessage result = mapMessage(mapper, "{\"is_deleted\": true, \"name\": \"alice\"}");
        assertEquals("index", result.parsedPayloadMap().get("_op_type"));
    }

    public void testOpTypeFieldMissing_DefaultsToIndex() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "is_deleted");
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "true");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage result = mapMessage(mapper, "{\"name\": \"alice\"}");
        assertEquals("index", result.parsedPayloadMap().get("_op_type"));
    }

    // --- Validation: delete_value == create_value ---

    public void testDeleteAndCreateValueSame_ThrowsException() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "op");
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "REMOVE");
        settings.put(FieldMappingIngestionMessageMapper.CREATE_VALUE, "REMOVE");

        IllegalArgumentException e = expectThrows(IllegalArgumentException.class, () -> new FieldMappingIngestionMessageMapper(settings));
        assertTrue(e.getMessage().contains("cannot be the same"));
    }

    public void testDeleteValueWithoutOpTypeField_ThrowsException() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "true");

        IllegalArgumentException e = expectThrows(IllegalArgumentException.class, () -> new FieldMappingIngestionMessageMapper(settings));
        assertTrue(e.getMessage().contains("requires op_type_field to be configured"));
    }

    public void testCreateValueWithoutOpTypeField_ThrowsException() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.CREATE_VALUE, "INSERT");

        IllegalArgumentException e = expectThrows(IllegalArgumentException.class, () -> new FieldMappingIngestionMessageMapper(settings));
        assertTrue(e.getMessage().contains("requires op_type_field to be configured"));
    }

    // --- All fields configured together ---

    public void testAllFieldsConfigured() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.ID_FIELD, "user_id");
        settings.put(FieldMappingIngestionMessageMapper.VERSION_FIELD, "timestamp");
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "is_deleted");
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "true");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        ShardUpdateMessage result = mapMessage(
            mapper,
            "{\"user_id\": \"abc\", \"timestamp\": 123, \"is_deleted\": false, \"name\": \"alice\", \"age\": 30}"
        );

        Map<String, Object> payloadMap = result.parsedPayloadMap();
        assertEquals("abc", payloadMap.get("_id"));
        assertEquals("123", payloadMap.get("_version"));
        assertEquals("index", payloadMap.get("_op_type"));
        assertEquals(UNSET_AUTO_GENERATED_TIMESTAMP, result.autoGeneratedIdTimestamp());

        Map<String, Object> source = (Map<String, Object>) payloadMap.get("_source");
        assertEquals(2, source.size());
        assertEquals("alice", source.get("name"));
        assertEquals(30, source.get("age"));
        assertFalse(source.containsKey("user_id"));
        assertFalse(source.containsKey("timestamp"));
        assertFalse(source.containsKey("is_deleted"));
    }

    // --- Scalar validation tests ---

    public void testIdFieldWithNestedObject_ThrowsException() {
        Map<String, Object> settings = Map.of(FieldMappingIngestionMessageMapper.ID_FIELD, "user");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        IllegalArgumentException e = expectThrows(
            IllegalArgumentException.class,
            () -> mapMessage(mapper, "{\"user\": {\"name\": \"alice\"}, \"data\": \"value\"}")
        );
        assertTrue(e.getMessage().contains("field [user] must be a scalar value"));
    }

    public void testIdFieldWithArray_ThrowsException() {
        Map<String, Object> settings = Map.of(FieldMappingIngestionMessageMapper.ID_FIELD, "tags");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        IllegalArgumentException e = expectThrows(
            IllegalArgumentException.class,
            () -> mapMessage(mapper, "{\"tags\": [\"a\", \"b\"], \"name\": \"alice\"}")
        );
        assertTrue(e.getMessage().contains("field [tags] must be a scalar value"));
    }

    public void testVersionFieldWithNestedObject_ThrowsException() {
        Map<String, Object> settings = Map.of(FieldMappingIngestionMessageMapper.VERSION_FIELD, "meta");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        IllegalArgumentException e = expectThrows(
            IllegalArgumentException.class,
            () -> mapMessage(mapper, "{\"meta\": {\"ts\": 123}, \"name\": \"alice\"}")
        );
        assertTrue(e.getMessage().contains("field [meta] must be a scalar value"));
    }

    public void testOpTypeFieldWithNestedObject_ThrowsException() {
        Map<String, Object> settings = new HashMap<>();
        settings.put(FieldMappingIngestionMessageMapper.OP_TYPE_FIELD, "status");
        settings.put(FieldMappingIngestionMessageMapper.DELETE_VALUE, "expired");
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(settings);

        IllegalArgumentException e = expectThrows(
            IllegalArgumentException.class,
            () -> mapMessage(mapper, "{\"status\": {\"deleted\": true}, \"name\": \"alice\"}")
        );
        assertTrue(e.getMessage().contains("field [status] must be a scalar value"));
    }

    // --- Edge cases ---

    public void testNullMapperSettings() {
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(null);

        ShardUpdateMessage result = mapMessage(mapper, "{\"name\": \"alice\"}");

        Map<String, Object> payloadMap = result.parsedPayloadMap();
        assertNotNull(payloadMap.get("_id"));
        assertEquals("index", payloadMap.get("_op_type"));

        Map<String, Object> source = (Map<String, Object>) payloadMap.get("_source");
        assertEquals("alice", source.get("name"));
    }

    public void testInvalidJson() {
        FieldMappingIngestionMessageMapper mapper = new FieldMappingIngestionMessageMapper(Collections.emptyMap());
        byte[] payloadBytes = "not valid json".getBytes(StandardCharsets.UTF_8);
        IngestionShardPointer pointer = new FakeIngestionSource.FakeIngestionShardPointer(1);
        Message message = new FakeIngestionSource.FakeIngestionMessage(payloadBytes);

        expectThrows(Exception.class, () -> mapper.mapAndProcess(pointer, message));
    }
}
