[[brew]]
=== Install {opensearch} on macOS with Homebrew

Elastic publishes Homebrew formulae so you can install {opensearch} with the
https://brew.sh/[Homebrew] package manager.

To install with Homebrew, you first need to tap the
Elastic Homebrew repository:

[source,sh]
-------------------------
brew tap elastic/tap
-------------------------

Once you've tapped the Elastic Homebrew repo, you can use `brew install` to
install the default distribution of {opensearch}:

[source,sh]
-------------------------
brew install elastic/tap/opensearch-full
-------------------------

This installs the most recently released default distribution of {opensearch}.
To install the OSS distribution, specify `opensearch/tap/opensearch-oss`.

[[brew-layout]]
==== Directory layout for Homebrew installs

When you install {opensearch} with `brew install` the config files, logs,
and data directory are stored in the following locations.

[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | OpenSearch home directory or `$OPENSEARCH_HOME`
  | /usr/local/var/homebrew/linked/opensearch-full
 d|

| bin
  | Binary scripts including `opensearch` to start a node
    and `opensearch-plugin` to install plugins
  | /usr/local/var/homebrew/linked/opensearch-full/bin
 d|

| conf
  | Configuration files including `opensearch.yml`
  | /usr/local/etc/opensearch
  | <<config-files-location,OPENSEARCH_PATH_CONF>>

| data
  | The location of the data files of each index / shard allocated
    on the node. Can hold multiple locations.
  | /usr/local/var/lib/opensearch
  | path.data

| logs
  | Log files location.
  | /usr/local/var/log/opensearch
  | path.logs

| plugins
  | Plugin files location. Each plugin will be contained in a subdirectory.
  | /usr/local/var/homebrew/linked/opensearch/plugins
  |

|=======================================================================

include::next-steps.asciidoc[]
