[[deb]]
=== Install OpenSearch with Debian Package

The Debian package for OpenSearch can be <<install-deb,downloaded from our website>>
or from our <<deb-repo,APT repository>>. It can be used to install
OpenSearch on any Debian-based system such as Debian and Ubuntu.

include::license.asciidoc[]

// TODO(OpenSearch): Correct the website url in this page
The latest stable version of OpenSearch can be found on the
link:/downloads/opensearch[Download OpenSearch] page. Other versions can
be found on the link:/downloads/past-releases[Past Releases page].

NOTE: OpenSearch includes a bundled version of https://openjdk.java.net[OpenJDK]
from the JDK maintainers (GPLv2+CE). To use your own version of Java,
see the <<jvm-version, JVM version requirements>>

[[deb-key]]
==== Import the OpenSearch PGP Key

include::key.asciidoc[]

// TODO(OpenSearch): Correct the website url in this page
[source,sh]
-------------------------
wget -qO - https://artifacts.opensearch.org/GPG-KEY-opensearch | sudo apt-key add -
-------------------------

[[deb-repo]]
==== Installing from the APT repository

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearch has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

You may need to install the `apt-transport-https` package on Debian before proceeding:

[source,sh]
--------------------------------------------------
sudo apt-get install apt-transport-https
--------------------------------------------------

Save the repository definition to  +/etc/apt/sources.list.d/opensearch-{major-version}.list+:

ifeval::["{release-state}"=="released"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.opensearch.org/packages/{major-version}/apt stable main" | sudo tee /etc/apt/sources.list.d/opensearch-{major-version}.list
--------------------------------------------------

endif::[]

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.opensearch.org/packages/{major-version}-prerelease/apt stable main" | sudo tee /etc/apt/sources.list.d/opensearch-{major-version}.list
--------------------------------------------------

endif::[]


[NOTE]
==================================================

These instructions do not use `add-apt-repository` for several reasons:

. `add-apt-repository` adds entries to the system `/etc/apt/sources.list` file
  rather than a clean per-repository file in `/etc/apt/sources.list.d`
. `add-apt-repository` is not part of the default install on many distributions
  and requires a number of non-default dependencies.
. Older versions of `add-apt-repository` always add a `deb-src` entry which
  will cause errors because we do not provide a source package. If you have added
  the `deb-src` entry, you will see an error like the following until you delete
  the `deb-src` line:

    Unable to find expected entry 'main/source/Sources' in Release file
    (Wrong sources.list entry or malformed file)

==================================================

You can install the OpenSearch Debian package with:

[source,sh]
--------------------------------------------------
sudo apt-get update && sudo apt-get install opensearch
--------------------------------------------------

[WARNING]
==================================================
If two entries exist for the same OpenSearch repository, you will see an error like this during `apt-get update`:

["literal",subs="attributes,callouts"]

Duplicate sources.list entry https://artifacts.opensearch.org/packages/{major-version}/apt/ ...`

Examine +/etc/apt/sources.list.d/opensearch-{major-version}.list+ for the duplicate entry or locate the duplicate entry amongst the files in `/etc/apt/sources.list.d/` and the `/etc/apt/sources.list` file.
==================================================

endif::[]

include::skip-set-kernel-parameters.asciidoc[]

ifeval::["{release-state}"!="unreleased"]

[NOTE]
==================================================

An alternative package which contains only features that are available under the
Apache 2.0 license is also available. To install it, use the following sources list:

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.opensearch.org/packages/oss-{major-version}-prerelease/apt stable main" | sudo tee /etc/apt/sources.list.d/opensearch-{major-version}.list
--------------------------------------------------

endif::[]

ifeval::["{release-state}"!="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb https://artifacts.opensearch.org/packages/oss-{major-version}/apt stable main" | sudo tee /etc/apt/sources.list.d/opensearch-{major-version}.list
--------------------------------------------------

endif::[]

==================================================

endif::[]

[[install-deb]]
==== Download and install the Debian package manually

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearch has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

The Debian package for OpenSearch v{version} can be downloaded from the website and installed as follows:

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.opensearch.org/downloads/opensearch/opensearch-{version}-amd64.deb
wget https://artifacts.opensearch.org/downloads/opensearch/opensearch-{version}-amd64.deb.sha512
shasum -a 512 -c opensearch-{version}-amd64.deb.sha512 <1>
sudo dpkg -i opensearch-{version}-amd64.deb
--------------------------------------------
<1> Compares the SHA of the downloaded Debian package and the published checksum, which should output
    `opensearch-{version}-amd64.deb: OK`.

Alternatively, you can download the following package, which contains only
features that are available under the Apache 2.0 license:
https://artifacts.opensearch.org/downloads/opensearch/opensearch-oss-{version}-amd64.deb

endif::[]

[[deb-sysv-init-vs-systemd]]
==== SysV `init` vs `systemd`

include::init-systemd.asciidoc[]

[[deb-running-init]]
include::deb-init.asciidoc[]

[[deb-running-systemd]]
include::systemd.asciidoc[]

[[deb-check-running]]
include::check-running.asciidoc[]

[[deb-configuring]]
==== Configuring OpenSearch

include::etc-elasticsearch.asciidoc[]

The Debian package also has a system configuration file (`/etc/default/opensearch`),
which allows you to set the following parameters:

include::sysconfig-file.asciidoc[]

NOTE: Distributions that use `systemd` require that system resource limits be
configured via `systemd` rather than via the `/etc/sysconfig/opensearch`
file.  See <<systemd>> for more information.

[[deb-layout]]
==== Directory layout of Debian package

The Debian package places config files, logs, and the data directory in the appropriate
locations for a Debian-based system:


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | OpenSearch home directory or `$OPENSEARCH_HOME`
  | /usr/share/opensearch
 d|

| bin
  | Binary scripts including `opensearch` to start a node
    and `opensearch-plugin` to install plugins
  | /usr/share/opensearch/bin
 d|

| conf
  | Configuration files including `opensearch.yml`
  | /etc/opensearch
  | <<config-files-location,OPENSEARCH_PATH_CONF>>

| conf
  | Environment variables including heap size, file descriptors.
  | /etc/default/opensearch
 d|

| data
  | The location of the data files of each index / shard allocated
    on the node. Can hold multiple locations.
  | /var/lib/opensearch
  | path.data

| jdk
  | The bundled Java Development Kit used to run OpenSearch. Can
    be overridden by setting the `JAVA_HOME` environment variable
    in `/etc/default/opensearch`.
  | /usr/share/opensearch/jdk
 d|

| logs
  | Log files location.
  | /var/log/opensearch
  | path.logs

| plugins
  | Plugin files location. Each plugin will be contained in a subdirectory.
  | /usr/share/opensearch/plugins
  |

| repo
  | Shared file system repository locations. Can hold multiple locations. A file system repository can be placed in to any subdirectory of any directory specified here.
 d| Not configured
  | path.repo

|=======================================================================

include::next-steps.asciidoc[]
