[[targz]]
=== Install OpenSearch from archive on Linux or MacOS

OpenSearch is as a `.tar.gz` archive for Linux and MacOS. 

// TODO(OpenSearch): Correct the links
The latest stable version of OpenSearch can be found on the
link:/downloads/elasticsearch[Download OpenSearch] page.
Other versions can be found on the
link:/downloads/past-releases[Past Releases page].

NOTE: OpenSearch includes a bundled version of https://openjdk.java.net[OpenJDK]
from the JDK maintainers (GPLv2+CE). To use your own version of Java,
see the <<jvm-version, JVM version requirements>>

[[install-linux]]
==== Download and install archive for Linux

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearch has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

The Linux archive for OpenSearch v{version} can be downloaded and installed as follows:

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{version}-linux-x86_64.tar.gz
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{version}-linux-x86_64.tar.gz.sha512
shasum -a 512 -c opensearch-{version}-linux-x86_64.tar.gz.sha512 <1>
tar -xzf opensearch-{version}-linux-x86_64.tar.gz
cd opensearch-{version}/ <2>
--------------------------------------------
<1> Compares the SHA of the downloaded `.tar.gz` archive and the published checksum, which should output
    `opensearch-{version}-linux-x86_64.tar.gz: OK`.
<2> This directory is known as `$OPENSEARCH_HOME`.

Alternatively, you can download the following package, which includes only 
Apache 2.0 licensed code: 
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-{version}-linux-x86_64.tar.gz

endif::[]

[[install-macos]]
==== Download and install archive for MacOS

ifeval::["{release-state}"=="unreleased"]

Version {version} of OpenSearch has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

The MacOS archive for OpenSearch v{version} can be downloaded and installed as follows:

["source","sh",subs="attributes"]
--------------------------------------------
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{version}-darwin-x86_64.tar.gz
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{version}-darwin-x86_64.tar.gz.sha512
shasum -a 512 -c opensearch-{version}-darwin-x86_64.tar.gz.sha512 <1>
tar -xzf opensearch-{version}-darwin-x86_64.tar.gz
cd opensearch-{version}/ <2>
--------------------------------------------
<1> Compares the SHA of the downloaded `.tar.gz` archive and the published checksum, which should output
    `opensearch-{version}-darwin-x86_64.tar.gz: OK`.
<2> This directory is known as `$OPENSEARCH_HOME`.

Alternatively, you can download the following package, which includes only 
Apache 2.0 licensed code: 
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-{version}-darwin-x86_64.tar.gz

endif::[]

[[targz-running]]
include::targz-start.asciidoc[]

include::check-running.asciidoc[]

Log printing to `stdout` can be disabled using the `-q` or `--quiet`
option on the command line.

[[setup-installation-daemon]]
include::targz-daemon.asciidoc[]

[[targz-configuring]]
==== Configuring OpenSearch on the command line

OpenSearch loads its configuration from the `$OPENSEARCH_HOME/config/opensearch.yml`
file by default.  The format of this config file is explained in
<<settings>>.

Any settings that can be specified in the config file can also be specified on
the command line, using the `-E` syntax as follows:

[source,sh]
--------------------------------------------
./bin/opensearch -d -Ecluster.name=my_cluster -Enode.name=node_1
--------------------------------------------

TIP: Typically, any cluster-wide settings (like `cluster.name`) should be
added to the `opensearch.yml` config file, while any node-specific settings
such as `node.name` could be specified on the command line.

[[targz-layout]]
==== Directory layout of archives

The archive distributions are entirely self-contained. All files and
directories are, by default, contained within `$OPENSEARCH_HOME` -- the directory
created when unpacking the archive.

This is very convenient because you don't have to create any directories to
start using OpenSearch, and uninstalling OpenSearch is as easy as
removing the `$OPENSEARCH_HOME` directory.  However, it is advisable to change the
default locations of the config directory, the data directory, and the logs
directory so that you do not delete important data later on.


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | OpenSearch home directory or `$OPENSEARCH_HOME`
 d| Directory created by unpacking the archive
  |

| bin
  | Binary scripts including `opensearch` to start a node
    and `opensearch-plugin` to install plugins
  | $OPENSEARCH_HOME/bin
 d|

| conf
  | Configuration files including `opensearch.yml`
  | $OPENSEARCH_HOME/config
  | <<config-files-location,ES_PATH_CONF>>

| data
  | The location of the data files of each index / shard allocated
    on the node. Can hold multiple locations.
  | $OPENSEARCH_HOME/data
  | path.data

| logs
  | Log files location.
  | $OPENSEARCH_HOME/logs
  | path.logs

| plugins
  | Plugin files location. Each plugin will be contained in a subdirectory.
  | $OPENSEARCH_HOME/plugins
  |

| repo
  | Shared file system repository locations. Can hold multiple locations. A file system repository can be placed in to any subdirectory of any directory specified here.
 d| Not configured
  | path.repo

|=======================================================================


include::next-steps.asciidoc[]
