/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

package org.opensearch.catalog;

import org.opensearch.cluster.metadata.IndexMetadata;
import org.opensearch.common.annotation.ExperimentalApi;
import org.opensearch.core.index.shard.ShardId;
import org.opensearch.index.store.RemoteSegmentStoreDirectory;

import java.io.Closeable;
import java.io.IOException;

/**
 * Client for publishing index data and metadata to an external catalog.
 * <p>
 * Implementations are provided by plugins via {@link org.opensearch.plugins.CatalogPlugin}.
 * A publish proceeds in three phases:
 * <ol>
 *   <li>{@link #startPublishForIndex} — once on the cluster manager to set up catalog state.</li>
 *   <li>{@link #copyShard} — once per primary shard to copy data files and register them.</li>
 *   <li>{@link #finalizePublish} — once after all shards finish, for post-publish bookkeeping.</li>
 * </ol>
 *
 * @opensearch.experimental
 */
@ExperimentalApi
public interface CatalogMetadataClient extends Closeable {

    /**
     * Prepares the catalog for publishing an index. Creates or loads the catalog table,
     * infers schema from {@code indexMetadata} on first create, and persists the metadata.
     * Called once on the cluster manager before any shard publish. Must be idempotent.
     *
     * @param indexName      name of the OpenSearch index being published
     * @param indexMetadata  index metadata (mappings, settings) to persist in the catalog
     * @throws IOException   if catalog setup fails
     */
    void startPublishForIndex(String indexName, IndexMetadata indexMetadata) throws IOException;

    /**
     * Copies data files for a single shard to the catalog warehouse. The plugin
     * discovers committed files from {@code remoteDirectory}, streams the ones it needs
     * into the warehouse, and registers them with the catalog.
     * <p>
     * {@link #startPublishForIndex} must have been called for {@code shardId}'s index first.
     *
     * @param publishId        correlation id for this publish. Generated by the orchestrator
     *                         and shared by all shard invocations of the same logical publish.
     *                         Plugins may use it to key any per-publish state (e.g. a write id
     *                         handed to the catalog) and to correlate retries.
     * @param shardId          primary shard being copied — index name and UUID are available via
     *                         {@link ShardId#getIndex()}
     * @param remoteDirectory  remote segment store directory for the shard
     * @throws IOException     if file read, warehouse write, or catalog registration fails
     */
    void copyShard(
        String publishId,
        ShardId shardId,
        RemoteSegmentStoreDirectory remoteDirectory
    ) throws IOException;

    /**
     * Called once after all shards complete. {@code success} is true when every shard's
     * {@link #copyShard} returned without error. Implementations use this to stamp a
     * completion marker on success, or rollback partial commits on failure. This method
     * also handles the cancel path — a user-initiated cancellation rolls back via the
     * same {@code success=false} invocation. Default is no-op.
     *
     * @param indexName  name of the index that was published
     * @param success    whether all shards published successfully
     * @throws IOException if the finalization fails
     */
    default void finalizePublish(String indexName, boolean success) throws IOException {}

    /**
     * Reads index metadata previously persisted by {@link #startPublishForIndex}.
     *
     * @param indexName  name of the index
     * @return the persisted index metadata, or {@code null} if not published
     * @throws IOException if the catalog read fails
     */
    IndexMetadata getMetadata(String indexName) throws IOException;

    /**
     * Releases resources held by the client.
     */
    @Override
    void close() throws IOException;
}
