/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

package org.opensearch.indices.pollingingest.mappers;

import org.opensearch.common.Nullable;
import org.opensearch.common.util.RequestUtils;
import org.opensearch.index.IngestionShardPointer;
import org.opensearch.index.Message;
import org.opensearch.indices.pollingingest.IngestionUtils;
import org.opensearch.indices.pollingingest.ShardUpdateMessage;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import static org.opensearch.action.index.IndexRequest.UNSET_AUTO_GENERATED_TIMESTAMP;
import static org.opensearch.indices.pollingingest.MessageProcessorRunnable.ID;
import static org.opensearch.indices.pollingingest.MessageProcessorRunnable.OP_TYPE;
import static org.opensearch.indices.pollingingest.MessageProcessorRunnable.SOURCE;

/**
 * Mapper implementation that extracts document metadata ({@code _id}, {@code _version}, {@code _op_type})
 * from configurable top-level fields in the raw message payload. The remaining fields become the document
 * {@code _source}.
 *
 * <p>Mapper settings:
 * <ul>
 *   <li>{@code id_field} — source field to use as document {@code _id}. If absent, ID is auto-generated.</li>
 *   <li>{@code version_field} — source field to use as document {@code _version} with external versioning.</li>
 *   <li>{@code op_type_field} — source field to determine operation type.</li>
 *   <li>{@code op_type_field.delete_value} — the value of {@code op_type_field} that indicates a delete operation.
 *       If not configured, the field is parsed as a boolean ({@code true}/{@code "true"} → delete).
 *       If configured, the field value is compared as a string: match → delete, no match → index.</li>
 * </ul>
 */
public class FieldMappingIngestionMessageMapper implements IngestionMessageMapper {

    /** Mapper setting key: source field to use as document _id */
    public static final String ID_FIELD = "id_field";
    /** Mapper setting key: source field to use as document _version */
    public static final String VERSION_FIELD = "version_field";
    /** Mapper setting key: source field to determine operation type (index vs delete) */
    public static final String OP_TYPE_FIELD = "op_type_field";
    /** Mapper setting key: the value of op_type_field that indicates a delete operation */
    public static final String DELETE_VALUE = "op_type_field.delete_value";

    /** Valid mapper_settings keys for this mapper type */
    public static final Set<String> VALID_SETTINGS = Set.of(ID_FIELD, VERSION_FIELD, OP_TYPE_FIELD, DELETE_VALUE);

    private static final String OP_TYPE_INDEX = "index";
    private static final String OP_TYPE_DELETE = "delete";

    @Nullable
    private final String idField;
    @Nullable
    private final String versionField;
    @Nullable
    private final String opTypeField;
    @Nullable
    private final String deleteValue;

    /**
     * Creates a FieldMappingIngestionMessageMapper from mapper settings.
     *
     * @param mapperSettings the mapper settings map containing id_field, version_field, op_type_field,
     *                       and optionally op_type_field.delete_value
     */
    public FieldMappingIngestionMessageMapper(Map<String, Object> mapperSettings) {
        this.idField = mapperSettings != null ? (String) mapperSettings.get(ID_FIELD) : null;
        this.versionField = mapperSettings != null ? (String) mapperSettings.get(VERSION_FIELD) : null;
        this.opTypeField = mapperSettings != null ? (String) mapperSettings.get(OP_TYPE_FIELD) : null;
        this.deleteValue = mapperSettings != null ? (String) mapperSettings.get(DELETE_VALUE) : null;
    }

    @Override
    public ShardUpdateMessage mapAndProcess(IngestionShardPointer pointer, Message message) throws IllegalArgumentException {
        Map<String, Object> rawPayload = IngestionUtils.getParsedPayloadMap((byte[]) message.getPayload());
        Map<String, Object> payloadMap = new HashMap<>();

        // Extract _id
        long autoGeneratedIdTimestamp = UNSET_AUTO_GENERATED_TIMESTAMP;
        if (idField != null && rawPayload.containsKey(idField)) {
            Object idValue = rawPayload.remove(idField);
            validateScalar(idField, idValue);
            String idStr = String.valueOf(idValue);
            if (idStr.isEmpty() || "null".equals(idStr)) {
                // Null or empty ID — fall back to auto-generation
                String id = RequestUtils.generateID();
                payloadMap.put(ID, id);
                autoGeneratedIdTimestamp = System.currentTimeMillis();
            } else {
                payloadMap.put(ID, idStr);
            }
        } else {
            String id = RequestUtils.generateID();
            payloadMap.put(ID, id);
            autoGeneratedIdTimestamp = System.currentTimeMillis();
        }

        // Extract _version
        if (versionField != null && rawPayload.containsKey(versionField)) {
            Object versionValue = rawPayload.remove(versionField);
            validateScalar(versionField, versionValue);
            payloadMap.put("_version", String.valueOf(versionValue));
        }

        // Extract _op_type
        if (opTypeField != null && rawPayload.containsKey(opTypeField)) {
            Object val = rawPayload.remove(opTypeField);
            validateScalar(opTypeField, val);
            String stringVal = String.valueOf(val);
            boolean isDelete;
            if (deleteValue != null) {
                // Compare against configured delete value
                isDelete = deleteValue.equals(stringVal);
            } else {
                // Default: parse as boolean
                isDelete = Boolean.parseBoolean(stringVal);
            }
            payloadMap.put(OP_TYPE, isDelete ? OP_TYPE_DELETE : OP_TYPE_INDEX);
        } else {
            payloadMap.put(OP_TYPE, OP_TYPE_INDEX);
        }

        // Remaining fields become _source
        payloadMap.put(SOURCE, rawPayload);

        return new ShardUpdateMessage(pointer, message, payloadMap, autoGeneratedIdTimestamp);
    }

    /**
     * Validates that a field value is a scalar type (string, number, boolean) and not a nested object or array.
     */
    private static void validateScalar(String fieldName, Object value) {
        if (value instanceof Map || value instanceof Iterable) {
            throw new IllegalArgumentException(
                "field ["
                    + fieldName
                    + "] must be a scalar value (string, number, or boolean), but found: "
                    + value.getClass().getSimpleName()
            );
        }
    }
}
