[[install-opensearch]]
== Installing OpenSearch

[discrete]
=== Installing OpenSearch Yourself

OpenSearch is provided in the following package formats:

[horizontal]
Linux and MacOS `tar.gz` archives::

The `tar.gz` archives are available for installation on any Linux distribution and MacOS.
+
<<targz>>

Windows `.zip` archive::

The `zip` archive is suitable for installation on Windows.
+
<<zip-windows>>

`deb`::

The `deb` package is suitable for Debian, Ubuntu, and other Debian-based
systems.  Debian packages may be downloaded from the OpenSearch website or
from our Debian repository.
+
<<deb>>

`rpm`::

The `rpm` package is suitable for installation on Red Hat, Centos, SLES,
OpenSuSE and other RPM-based systems.  RPMs may be downloaded from the
OpenSearch website or from our RPM repository.
+
<<rpm>>

`docker`::

Images are available for running OpenSearch as Docker containers. They may be
downloaded from the Elastic Docker Registry.
+
{ref}/docker.html[Install {opensearch} with Docker]

`brew`::

Formulae are available from the Elastic Homebrew tap for installing
{opensearch} on macOS with the Homebrew package manager.
+
{ref}/brew.html[Install {opensearch} on macOS with Homebrew]

[discrete]
[[config-mgmt-tools]]
=== Configuration Management Tools

We also provide the following configuration management tools to help with
large deployments:

[horizontal]
Puppet:: https://github.com/elastic/puppet-elasticsearch[puppet-elasticsearch]
Chef::   https://github.com/elastic/cookbook-elasticsearch[cookbook-elasticsearch]
Ansible:: https://github.com/elastic/ansible-elasticsearch[ansible-elasticsearch]


include::install/targz.asciidoc[]

include::install/zip-windows.asciidoc[]

include::install/deb.asciidoc[]

include::install/rpm.asciidoc[]

include::install/docker.asciidoc[]

include::install/brew.asciidoc[]
