/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

package org.opensearch.rest.pagination;

/**
 * To be implemented by tokens getting returned/generated by {@link PaginationStrategy}.
 *
 * @opensearch.internal
 */
public interface PageToken {

    String generateEncryptedToken();
}
