services:
  wazuh-indexer-builder:
    image: wazuh-indexer-builder:${VERSION}
    container_name: wazuh-indexer-builder_${VERSION}
    build:
      context: ./../..
      dockerfile: ${REPO_PATH}/build-scripts/builder/Dockerfile
    environment:
      - INDEXER_PLUGINS_BRANCH=${INDEXER_PLUGINS_BRANCH:-main}
      - INDEXER_REPORTING_BRANCH=${INDEXER_REPORTING_BRANCH:-main}
      - SECURITY_ANALYTICS_BRANCH=${SECURITY_ANALYTICS_BRANCH:-main}
      - NOTIFICATIONS_BRANCH=${NOTIFICATIONS_BRANCH:-main}
      - COMMON_UTILS_BRANCH=${COMMON_UTILS_BRANCH:-main}
      - ENGINE_TARBALL=${ENGINE_TARBALL:-}
      - REVISION=${REVISION:-0}
      - IS_STAGE=${IS_STAGE:-false}
      - DISTRIBUTION=${DISTRIBUTION:-rpm}
      - ARCHITECTURE=${ARCHITECTURE:-x64}
    volumes:
      - ${REPO_PATH}:/home/wazuh-indexer
      - wazuh-indexer-plugins:/home/wazuh-indexer/wazuh-indexer-plugins
      - wazuh-indexer-reporting:/home/wazuh-indexer/wazuh-indexer-reporting
      - wazuh-indexer-security-analytics:/home/wazuh-indexer/wazuh-indexer-security-analytics
      - wazuh-indexer-notifications:/home/wazuh-indexer/wazuh-indexer-notifications
      - wazuh-indexer-common-utils:/home/wazuh-indexer/wazuh-indexer-common-utils
      - ${ENGINE_TARBALL:-/dev/null}:/tmp/engine-tarball.tar.gz:ro
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    user: "1000:1000"
    working_dir: /home/wazuh-indexer
volumes:
  wazuh-indexer-plugins:
  wazuh-indexer-reporting:
  wazuh-indexer-security-analytics:
  wazuh-indexer-notifications:
  wazuh-indexer-common-utils: