registries:
  gradle-maven:
    type: maven-repository
    url: https://repo1.maven.org/maven2
updates:
  - directory: /
    open-pull-requests-limit: 1
    package-ecosystem: gradle
    registries:
      - gradle-maven
    ignore:
      - dependency-name: "com.google.cloud:google-cloud-storage"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.google.api-client:google-api-client"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: weekly
    labels:
      - "dependabot"
      - "dependencies"
      - "skip-diff-analyzer"
  - directory: /
    open-pull-requests-limit: 1
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "dependencies"
      - "skip-diff-analyzer"
version: 2
