[[cat-count]]
=== cat count API
++++
<titleabbrev>cat count</titleabbrev>
++++

Provides quick access to a document count for an index or an
entire cluster.

NOTE: The document count only includes live documents, not deleted documents
which have not yet been removed by the merge process.


[[cat-count-api-request]]
==== {api-request-title}

`GET /_cat/count/<target>`

`GET /_cat/count`

[[cat-count-api-path-params]]
==== {api-path-parms-title}

`<target>`::
(Optional, string)
Comma-separated list of indices and index aliases used to limit
the request. Wildcard expressions (`*`) are supported.
+
To target all indices in a cluster, omit this parameter or use
`_all` or `*`.

[[cat-count-api-query-params]]
==== {api-query-parms-title}

include::{opensearch-repo-dir}/rest-api/common-parms.asciidoc[tag=http-format]

include::{opensearch-repo-dir}/rest-api/common-parms.asciidoc[tag=cat-h]

include::{opensearch-repo-dir}/rest-api/common-parms.asciidoc[tag=help]

include::{opensearch-repo-dir}/rest-api/common-parms.asciidoc[tag=cat-s]

include::{opensearch-repo-dir}/rest-api/common-parms.asciidoc[tag=cat-v]


[[cat-count-api-example]]
==== {api-examples-title}

[[cat-count-api-example-ind]]
===== Example with an individual index

The following `count` API request retrieves the document count for the 
`my-index-000001` index.

[source,console]
--------------------------------------------------
GET /_cat/count/my-index-000001?v=true
--------------------------------------------------
// TEST[setup:my_index_big]


The API returns the following response:

[source,txt]
--------------------------------------------------
epoch      timestamp count
1475868259 15:24:20  120
--------------------------------------------------
// TESTRESPONSE[s/1475868259 15:24:20/\\d+ \\d+:\\d+:\\d+/ non_json]

[[cat-count-api-example-all]]
===== Example with all indices in a cluster

The following `count` API request retrieves the document count for all data
streams and indices in the cluster.

[source,console]
--------------------------------------------------
GET /_cat/count?v=true
--------------------------------------------------
// TEST[setup:my_index_big]
// TEST[s/^/POST test\/_doc\?refresh\n{"test": "test"}\n/]

The API returns the following response:

[source,txt]
--------------------------------------------------
epoch      timestamp count
1475868259 15:24:20  121
--------------------------------------------------
// TESTRESPONSE[s/1475868259 15:24:20/\\d+ \\d+:\\d+:\\d+/ non_json]
