[[release-notes-7.10.2]]
== {opensearch} version 7.10.2

Also see <<breaking-changes-7.10,Breaking changes in 7.10>>.

[discrete]
[[security-updates-7.10.2]]
=== Security updates

* An information disclosure flaw was found in the {opensearch} async search API.
Users who execute an async search will store the HTTP headers.
A user with the ability to read the `.tasks` index could obtain
sensitive request headers of other users in the cluster.
All versions of {opensearch} between 7.7.0 and 7.10.1 are affected by this flaw.
You must upgrade to {opensearch} version 7.10.2 to obtain the fix.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22132[CVE-2021-22132]

[[bug-7.10.2]]
[float]
=== Bug fixes

Engine::
* Fix the earliest last modified age of translog issue. {es-pull}64753[#64753]
* Fix the version and term field initialization error of NoOpResult {es-pull}66269[#66269] (issue: {es-issue}66267[#66267])

Features/Features::
* Make FilterAllocationDecider totally ignore tier-based allocation settings {es-pull}67019[#67019] (issue: {es-issue}66679[#66679])

Features/Ingest::
* Fix whitespace as a separator in CSV processor {es-pull}67045[#67045] (issue: {es-issue}67013[#67013])

Highlighting::
* Fix bug where fvh fragments could be loaded from wrong doc {es-pull}65641[#65641] (issues: {es-issue}60179[#60179], {es-issue}65533[#65533])

Infra/REST API::
* Fix cat tasks api params in spec and handler {es-pull}66272[#66272] (issue: {es-issue}59493[#59493])
* Mark Cat Tasks API as experimental in rest-api-spec {es-pull}66536[#66536] (issues: {es-issue}51628[#51628], {es-issue}65823[#65823])
* Mark Task APIs as experimental in rest-api-spec {es-pull}65823[#65823] (issue: {es-issue}51628[#51628])

Infra/Scripting::
* Fix static inner class resolution in Painless {es-pull}67027[#67027] (issue: {es-issue}66823[#66823])

Infra/Settings::
* Correctly determine defaults of settings which depend on other settings {es-pull}65989[#65989] (issue: {es-issue}47890[#47890])
* Do not interpret SecurityException in KeystoreAwareCommand {es-pull}65366[#65366]

Network::
* Ensure notify when proxy connections disconnect {es-pull}65697[#65697] (issue: {es-issue}65443[#65443])
* Fix AbstractClient#execute Listener Leak {es-pull}65415[#65415] (issue: {es-issue}65405[#65405])

Search::
* Fix regressions around nested hits and disabled _source {es-pull}66572[#66572] (issues: {es-issue}60494[#60494], {es-issue}66524[#66524])
* Make sure shared source always represents the top-level root document {es-pull}66725[#66725] (issues: {es-issue}60494[#60494], {es-issue}66577[#66577])

Snapshot/Restore::
* Also reroute after shard snapshot size fetch failure {es-pull}65436[#65436] (issues: {es-issue}61906[#61906], {es-issue}64372[#64372])


[[release-notes-7.10.1]]
== {opensearch} version 7.10.1

Also see <<breaking-changes-7.10,Breaking changes in 7.10>>.

[[known-issues-7.10.1]]
[discrete]
=== Known issues
* In {opensearch} 7.10.0 there were several regressions around loading nested documents. These have been addressed in {opensearch} 7.10.2.
** With multiple layers of nested `inner_hits`, we can fail to load the _source. ({es-issue}66577[#66577])
** With nested `inner_hits`, the fast vector highlighter may load snippets from the wrong document. ({es-issue}65533[#65533])
** When _source is disabled, we can fail load nested `inner_hits` and `top_hits`. ({es-issue}66572[#66572])

[[bug-7.10.1]]
[float]
=== Bug fixes

Allocation::
* Fix NPE in toString of FailedShard {es-pull}64770[#64770]

CRUD::
* Propogate rejected execution during bulk actions {es-pull}64842[#64842] (issue: {es-issue}64450[#64450])

Cluster Coordination::
* Fix up roles after rolling upgrade {es-pull}64693[#64693] (issue: {es-issue}62840[#62840])

Geo::
* Fix handling of null values in geo_point {es-pull}65307[#65307] (issue: {es-issue}65306[#65306])

Infra/Core::
* Fix date math hidden index resolution {es-pull}65236[#65236] (issue: {es-issue}65157[#65157])

Infra/Scripting::
* Fix Painless casting bug in compound assignment for String {es-pull}65329[#65329]
* Revert null-safe behavior to error at run-time instead of compile-time {es-pull}65099[#65099] (issue: {es-issue}65098[#65098])

Mapping::
* Correctly serialize search-as-you-type analyzer {es-pull}65359[#65359] (issue: {es-issue}65319[#65319])
* Unused boost parameter should not throw mapping exception {es-pull}64999[#64999] (issue: {es-issue}64982[#64982])

Search::
* Fix cacheability of custom LongValuesSource in TermsSetQueryBuilder {es-pull}65367[#65367]
* SourceValueFetcher should check all possible source fields {es-pull}65375[#65375]

Snapshot/Restore::
* Fix Broken Error Handling in CacheFile#acquire {es-pull}65342[#65342] (issue: {es-issue}65302[#65302])
* Fix Two Snapshot Clone State Machine Bugs {es-pull}65042[#65042]


[[release-notes-7.10.0]]
== {opensearch} version 7.10.0

Also see <<breaking-changes-7.10,Breaking changes in 7.10>>.

[[known-issues-7.10.0]]
[discrete]
=== Known issues

+
We have fixed this issue in {opensearch} 7.10.1 and later versions. For more details,
see {es-issue}65488[#65488].

* There were several regressions around loading nested documents. These have been addressed in {opensearch} 7.10.2.
** With multiple layers of nested `inner_hits`, we can fail to load the _source. ({es-issue}66577[#66577])
** With nested `inner_hits`, the fast vector highlighter may load snippets from the wrong document. ({es-issue}65533[#65533])
** When _source is disabled, we can fail load nested `inner_hits` and `top_hits`. ({es-issue}66572[#66572])

[[breaking-7.10.0]]
[float]
=== Breaking changes

Network::
* Set specific keepalive options by default on supported platforms {es-pull}59278[#59278]



[[breaking-java-7.10.0]]
[float]
=== Breaking Java changes

Mapping::
* Pass SearchLookup supplier through to fielddataBuilder {es-pull}61430[#61430] (issue: {es-issue}59332[#59332])



[[deprecation-7.10.0]]
[float]
=== Deprecations

Cluster Coordination::
* Deprecate and ignore join timeout {es-pull}60872[#60872] (issue: {es-issue}60873[#60873])

[[feature-7.10.0]]
[float]
=== New features

Aggregations::
* Add rate aggregation {es-pull}61369[#61369] (issue: {es-issue}60674[#60674])

Features/Features::
* Add data tiers (hot, warm, cold, frozen) as custom node roles {es-pull}60994[#60994] (issue: {es-issue}60848[#60848])
* Allocate newly created indices on data_hot tier nodes {es-pull}61342[#61342] (issue: {es-issue}60848[#60848])

Mapping::
* Introduce 64-bit unsigned long field type {es-pull}60050[#60050] (issue: {es-issue}32434[#32434])

Search::
* Add search 'fields' option to support high-level field retrieval {es-pull}60100[#60100] (issues: {es-issue}49028[#49028], {es-issue}55363[#55363])



[[enhancement-7.10.0]]
[float]
=== Enhancements

Aggregations::
* Adds hard_bounds to histogram aggregations {es-pull}59175[#59175] (issue: {es-issue}50109[#50109])
* Allocate slightly less per bucket {es-pull}59740[#59740]
* Improve reduction of terms aggregations {es-pull}61779[#61779] (issue: {es-issue}51857[#51857])
* Speed up date_histogram by precomputing ranges {es-pull}61467[#61467]

Analysis::
* Support ignore_keywords flag for word delimiter graph token filter {es-pull}59563[#59563] (issue: {es-issue}59491[#59491])

CRUD::
* Add configured indexing memory limit to node stats {es-pull}60342[#60342]
* Dedicated threadpool for system index writes {es-pull}61655[#61655]

Cluster Coordination::
* Add more useful toString on cluster state observers {es-pull}60277[#60277]
* Fail invalid incremental cluster state writes {es-pull}61030[#61030]
* Provide option to allow writes when master is down {es-pull}60605[#60605]

Distributed::
* Detect noop of update index settings {es-pull}61348[#61348]
* Thread safe clean up of LocalNodeModeListeners {es-pull}59932[#59932] (issue: {es-issue}59801[#59801])

Features/CAT APIs::
* Adding Hit counts and Miss counts for QueryCache exposed through REST API {es-pull}60114[#60114] (issue: {es-issue}48645[#48645])

Features/Features::
* Add aggregation list to node info {es-pull}60074[#60074] (issue: {es-issue}52057[#52057])
* Adding new `require_alias` option to indexing requests {es-pull}58917[#58917] (issue: {es-issue}55267[#55267])

Features/Ingest::
* Add network from MaxMind Geo ASN database {es-pull}61676[#61676]
* Allow_duplicates option for append processor {es-pull}61916[#61916] (issue: {es-issue}57543[#57543])
* Configurable output format for date processor {es-pull}61324[#61324] (issue: {es-issue}42523[#42523])
* Enhance the ingest node simulate verbose output  {es-pull}60433[#60433] (issue: {es-issue}56004[#56004])
* Per processor description for verbose simulate {es-pull}58207[#58207] (issue: {es-issue}57906[#57906])
* Preserve grok pattern ordering and add sort option {es-pull}61671[#61671] (issue: {es-issue}40819[#40819])

Features/Java High Level REST Client::
* HLRC: UpdateByQuery API with wait_for_completion being false {es-pull}58552[#58552] (issues: {es-issue}35202[#35202], {es-issue}46350[#46350])

Infra/Core::
* Deprecate REST access to System Indices {es-pull}60945[#60945]
* Speed up Compression Logic by Pooling Resources {es-pull}61358[#61358]
* System index reads in separate threadpool {es-pull}57936[#57936] (issues: {es-issue}37867[#37867], {es-issue}50251[#50251])

Infra/Logging::
* Do not create two loggers for DeprecationLogger {es-pull}58435[#58435]
* Header warning logging refactoring {es-pull}55941[#55941] (issues: {es-issue}52369[#52369], {es-issue}55699[#55699])
* Write deprecation logs to a data stream {es-pull}61484[#61484] (issues: {es-issue}46106[#46106], {es-issue}61474[#61474])

Infra/Packaging::
* Upgrade Centos version in Dockerfile to 8 {es-pull}59019[#59019]

Infra/Resiliency::
* Remove node from cluster when node locks broken {es-pull}61400[#61400] (issues: {es-issue}52680[#52680], {es-issue}58373[#58373])

Infra/Scripting::
* Augment String with sha1 and sha256 {es-pull}59671[#59671] (issue: {es-issue}59633[#59633])
* Converts casting and def support {es-pull}61350[#61350] (issue: {es-issue}59647[#59647])

Mapping::
* Add field type for version strings {es-pull}59773[#59773] (issue: {es-issue}48878[#48878])
* Allow [null] values in [null_value] {es-pull}61798[#61798] (issues: {es-issue}7978[#7978], {es-issue}58823[#58823])
* Allow metadata fields in the _source {es-pull}61590[#61590] (issue: {es-issue}58339[#58339])

Network::
* Improve deserialization failure logging {es-pull}60577[#60577] (issue: {es-issue}38939[#38939])
* Log and track open/close of transport connections {es-pull}60297[#60297]

Performance::
* Speed up empty highlighting many fields {es-pull}61860[#61860]

Search::
* Avoid reloading _source for every inner hit {es-pull}60494[#60494] (issue: {es-issue}32818[#32818])
* Cancel multisearch when http connection closed {es-pull}61399[#61399]
* Enable cancellation for msearch requests {es-pull}61337[#61337]
* Executes incremental reduce in the search thread pool {es-pull}58461[#58461] (issues: {es-issue}51857[#51857], {es-issue}53411[#53411])
* ParametrizedFieldMapper to run validators against default value {es-pull}60042[#60042] (issue: {es-issue}59332[#59332])
* Add case insensitive flag for "term" family of queries {es-pull}61596[#61596] (issue: {es-issue}61546[#61546])
* Add case insensitive support for regex queries {es-pull}59441[#59441]
* Tweak toXContent implementation of ParametrizedFieldMapper {es-pull}59968[#59968]
* Implement fields value fetching for the `text`, `search_as_you_type` and `token_count` field types {es-pull}63515[#63515]
* Make term/prefix/wildcard/regex query parsing more lenient, with respect to the `case_insensitive` flag {es-pull}63926[#63926] (issue: {es-issue}63893[#63893])

Snapshot/Restore::
* Add repositories metering API {es-pull}60371[#60371]
* Clone Snapshot API {es-pull}61839[#61839]
* Determine shard size before allocating shards recovering from snapshots {es-pull}61906[#61906]
* Introduce index based snapshot blob cache for Searchable Snapshots {es-pull}60522[#60522]
* Validate snapshot UUID during restore {es-pull}59601[#59601] (issue: {es-issue}50999[#50999])

Store::
* Report more details of unobtainable ShardLock {es-pull}61255[#61255] (issue: {es-issue}38807[#38807])


[[bug-7.10.0]]
[float]
=== Bug fixes

Aggregations::
* Fix AOOBE when setting min_doc_count to 0 in significant_terms {es-pull}60823[#60823] (issues: {es-issue}60683[#60683], {es-issue}60824[#60824])
* Make sure non-collecting aggs include sub-aggs {es-pull}64214[#64214] (issue: {es-issue}64142[#64142])
* Composite aggregation must check live docs when the index is sorted {es-pull}63864[#63864]
* Fix broken parent and child aggregator {es-pull}63811[#63811]

Allocation::
* Fix scheduling of ClusterInfoService#refresh {es-pull}59880[#59880]

CRUD::
* Propagate forceExecution when acquiring permit {es-pull}60634[#60634] (issue: {es-issue}60359[#60359])

Cluster Coordination::
* Reduce allocations when persisting cluster state {es-pull}61159[#61159]

Distributed::
* Fix cluster health rest api wait_for_no_initializing_shards bug {es-pull}58379[#58379]
* Fix cluster health when closing {es-pull}61709[#61709]

Engine::
* Fix estimate size of translog operations {es-pull}59206[#59206]

Features/Java Low Level REST Client::
* Handle non-default port in Cloud-Id {es-pull}61581[#61581]

Features/Stats::
* Remove sporadic min/max usage estimates from stats {es-pull}59755[#59755]

Geo::
* Fix wrong NaN comparison  {es-pull}61795[#61795] (issue: {es-issue}48207[#48207])

Infra/Core::
* Throws IndexNotFoundException in TransportGetAction for unknown System indices {es-pull}61785[#61785] (issue: {es-issue}57936[#57936])
* Handle missing logstash index exceptions {es-pull}63698[#63698]

Infra/Packaging::
* Allow running the Docker image with a non-default group {es-pull}61194[#61194] (issue: {es-issue}60864[#60864])
* Set the systemd initial timeout to 75 seconds {es-pull}60345[#60345] (issue: {es-issue}60140[#60140])

Mapping::
* Improve 'ignore_malformed' handling for dates {es-pull}60211[#60211] (issue: {es-issue}52634[#52634])

Network::
* Let `isInetAddress` utility understand the scope ID on ipv6 {es-pull}60172[#60172] (issue: {es-issue}60115[#60115])
* Suppress noisy SSL exceptions {es-pull}61359[#61359]

Search::
* Allows nanosecond resolution in search_after {es-pull}60328[#60328] (issue: {es-issue}52424[#52424])
* Consolidate validation for 'docvalue_fields' {es-pull}59473[#59473]
* Correct how field retrieval handles multifields and copy_to {es-pull}61309[#61309] (issue: {es-issue}61033[#61033])
* Apply boost only once for distance_feature query {es-pull}63767[#63767]
* Fixed NullPointerException in `significant_text` aggregation when field does not exist {es-pull}64144[#64144] (issue: {es-issue}64045[#64045])
* Fix async search to retry updates on version conflict {es-pull}63652[#63652] (issue: {es-issue}63213[#63213])
* Fix sorted query when date_nanos is used as the numeric_type {es-pull}64183[#64183] (issue: {es-issue}63719[#63719])

Snapshot/Restore::
* Avoid listener call under SparseFileTracker#mutex {es-pull}61626[#61626] (issue: {es-issue}61520[#61520])
* Ensure repo not in use for wildcard repo deletes {es-pull}60947[#60947]
* Fix Test Failure in testCorrectCountsForDoneShards {es-pull}60254[#60254] (issue: {es-issue}60247[#60247])
* Minimize cache file locking during prewarming {es-pull}61837[#61837] (issue: {es-issue}58658[#58658])
* Prevent snapshots to be mounted as system indices {es-pull}61517[#61517] (issue: {es-issue}60522[#60522])
* Make Searchable Snapshot's CacheFile Lock less {es-pull}63911[#63911] (issue: {es-issue}63586[#63586])
* Don't Generate an Index Setting History UUID unless it's supported {es-pull}64213[#64213] (issue: {es-issue}64152[#64152])



[[upgrade-7.10.0]]
[discrete]
=== Upgrades

Infra/Packaging::
* Upgrade bundled JDK to 15.0.1 and switch to AdoptOpenJDK {es-pull}64253[#64253]

Store::
* Upgrade to Lucene-8.7.0 {es-pull}64532[#64532]
