// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server/src/main/java/org/opensearch/extensions/proto/ExtensionRequest.proto

package org.opensearch.extensions.proto;

public final class ExtensionRequestOuterClass {
  private ExtensionRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.opensearch.extensions.proto.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQUEST_EXTENSION_CLUSTER_STATE = 0;</code>
     */
    REQUEST_EXTENSION_CLUSTER_STATE(0),
    /**
     * <code>REQUEST_EXTENSION_CLUSTER_SETTINGS = 1;</code>
     */
    REQUEST_EXTENSION_CLUSTER_SETTINGS(1),
    /**
     * <code>REQUEST_EXTENSION_REGISTER_REST_ACTIONS = 2;</code>
     */
    REQUEST_EXTENSION_REGISTER_REST_ACTIONS(2),
    /**
     * <code>REQUEST_EXTENSION_REGISTER_SETTINGS = 3;</code>
     */
    REQUEST_EXTENSION_REGISTER_SETTINGS(3),
    /**
     * <code>REQUEST_EXTENSION_ENVIRONMENT_SETTINGS = 4;</code>
     */
    REQUEST_EXTENSION_ENVIRONMENT_SETTINGS(4),
    /**
     * <code>REQUEST_EXTENSION_DEPENDENCY_INFORMATION = 5;</code>
     */
    REQUEST_EXTENSION_DEPENDENCY_INFORMATION(5),
    /**
     * <code>CREATE_COMPONENT = 6;</code>
     */
    CREATE_COMPONENT(6),
    /**
     * <code>ON_INDEX_MODULE = 7;</code>
     */
    ON_INDEX_MODULE(7),
    /**
     * <code>GET_SETTINGS = 8;</code>
     */
    GET_SETTINGS(8),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>REQUEST_EXTENSION_CLUSTER_STATE = 0;</code>
     */
    public static final int REQUEST_EXTENSION_CLUSTER_STATE_VALUE = 0;
    /**
     * <code>REQUEST_EXTENSION_CLUSTER_SETTINGS = 1;</code>
     */
    public static final int REQUEST_EXTENSION_CLUSTER_SETTINGS_VALUE = 1;
    /**
     * <code>REQUEST_EXTENSION_REGISTER_REST_ACTIONS = 2;</code>
     */
    public static final int REQUEST_EXTENSION_REGISTER_REST_ACTIONS_VALUE = 2;
    /**
     * <code>REQUEST_EXTENSION_REGISTER_SETTINGS = 3;</code>
     */
    public static final int REQUEST_EXTENSION_REGISTER_SETTINGS_VALUE = 3;
    /**
     * <code>REQUEST_EXTENSION_ENVIRONMENT_SETTINGS = 4;</code>
     */
    public static final int REQUEST_EXTENSION_ENVIRONMENT_SETTINGS_VALUE = 4;
    /**
     * <code>REQUEST_EXTENSION_DEPENDENCY_INFORMATION = 5;</code>
     */
    public static final int REQUEST_EXTENSION_DEPENDENCY_INFORMATION_VALUE = 5;
    /**
     * <code>CREATE_COMPONENT = 6;</code>
     */
    public static final int CREATE_COMPONENT_VALUE = 6;
    /**
     * <code>ON_INDEX_MODULE = 7;</code>
     */
    public static final int ON_INDEX_MODULE_VALUE = 7;
    /**
     * <code>GET_SETTINGS = 8;</code>
     */
    public static final int GET_SETTINGS_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return REQUEST_EXTENSION_CLUSTER_STATE;
        case 1: return REQUEST_EXTENSION_CLUSTER_SETTINGS;
        case 2: return REQUEST_EXTENSION_REGISTER_REST_ACTIONS;
        case 3: return REQUEST_EXTENSION_REGISTER_SETTINGS;
        case 4: return REQUEST_EXTENSION_ENVIRONMENT_SETTINGS;
        case 5: return REQUEST_EXTENSION_DEPENDENCY_INFORMATION;
        case 6: return CREATE_COMPONENT;
        case 7: return ON_INDEX_MODULE;
        case 8: return GET_SETTINGS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.opensearch.extensions.proto.ExtensionRequestOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.opensearch.extensions.proto.RequestType)
  }

  public interface ExtensionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.opensearch.extensions.proto.ExtensionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.opensearch.extensions.proto.RequestType requestType = 1;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    int getRequestTypeValue();
    /**
     * <code>.org.opensearch.extensions.proto.RequestType requestType = 1;</code>
     * @return The requestType.
     */
    org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType getRequestType();

    /**
     * <code>string uniqiueId = 2;</code>
     * @return The uniqiueId.
     */
    java.lang.String getUniqiueId();
    /**
     * <code>string uniqiueId = 2;</code>
     * @return The bytes for uniqiueId.
     */
    com.google.protobuf.ByteString
        getUniqiueIdBytes();
  }
  /**
   * Protobuf type {@code org.opensearch.extensions.proto.ExtensionRequest}
   */
  public static final class ExtensionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.opensearch.extensions.proto.ExtensionRequest)
      ExtensionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExtensionRequest.newBuilder() to construct.
    private ExtensionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExtensionRequest() {
      requestType_ = 0;
      uniqiueId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExtensionRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.extensions.proto.ExtensionRequestOuterClass.internal_static_org_opensearch_extensions_proto_ExtensionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.extensions.proto.ExtensionRequestOuterClass.internal_static_org_opensearch_extensions_proto_ExtensionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest.class, org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest.Builder.class);
    }

    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private int requestType_ = 0;
    /**
     * <code>.org.opensearch.extensions.proto.RequestType requestType = 1;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    @java.lang.Override public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.org.opensearch.extensions.proto.RequestType requestType = 1;</code>
     * @return The requestType.
     */
    @java.lang.Override public org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType getRequestType() {
      org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType result = org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType.forNumber(requestType_);
      return result == null ? org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType.UNRECOGNIZED : result;
    }

    public static final int UNIQIUEID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uniqiueId_ = "";
    /**
     * <code>string uniqiueId = 2;</code>
     * @return The uniqiueId.
     */
    @java.lang.Override
    public java.lang.String getUniqiueId() {
      java.lang.Object ref = uniqiueId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uniqiueId_ = s;
        return s;
      }
    }
    /**
     * <code>string uniqiueId = 2;</code>
     * @return The bytes for uniqiueId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUniqiueIdBytes() {
      java.lang.Object ref = uniqiueId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uniqiueId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestType_ != org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType.REQUEST_EXTENSION_CLUSTER_STATE.getNumber()) {
        output.writeEnum(1, requestType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uniqiueId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uniqiueId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestType_ != org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType.REQUEST_EXTENSION_CLUSTER_STATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, requestType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uniqiueId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uniqiueId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest)) {
        return super.equals(obj);
      }
      org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest other = (org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest) obj;

      if (requestType_ != other.requestType_) return false;
      if (!getUniqiueId()
          .equals(other.getUniqiueId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestType_;
      hash = (37 * hash) + UNIQIUEID_FIELD_NUMBER;
      hash = (53 * hash) + getUniqiueId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.opensearch.extensions.proto.ExtensionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.opensearch.extensions.proto.ExtensionRequest)
        org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opensearch.extensions.proto.ExtensionRequestOuterClass.internal_static_org_opensearch_extensions_proto_ExtensionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opensearch.extensions.proto.ExtensionRequestOuterClass.internal_static_org_opensearch_extensions_proto_ExtensionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest.class, org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest.Builder.class);
      }

      // Construct using org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestType_ = 0;
        uniqiueId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opensearch.extensions.proto.ExtensionRequestOuterClass.internal_static_org_opensearch_extensions_proto_ExtensionRequest_descriptor;
      }

      @java.lang.Override
      public org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest getDefaultInstanceForType() {
        return org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest build() {
        org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest buildPartial() {
        org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest result = new org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestType_ = requestType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.uniqiueId_ = uniqiueId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest) {
          return mergeFrom((org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest other) {
        if (other == org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest.getDefaultInstance()) return this;
        if (other.requestType_ != 0) {
          setRequestTypeValue(other.getRequestTypeValue());
        }
        if (!other.getUniqiueId().isEmpty()) {
          uniqiueId_ = other.uniqiueId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                requestType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                uniqiueId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int requestType_ = 0;
      /**
       * <code>.org.opensearch.extensions.proto.RequestType requestType = 1;</code>
       * @return The enum numeric value on the wire for requestType.
       */
      @java.lang.Override public int getRequestTypeValue() {
        return requestType_;
      }
      /**
       * <code>.org.opensearch.extensions.proto.RequestType requestType = 1;</code>
       * @param value The enum numeric value on the wire for requestType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestTypeValue(int value) {
        requestType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.org.opensearch.extensions.proto.RequestType requestType = 1;</code>
       * @return The requestType.
       */
      @java.lang.Override
      public org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType getRequestType() {
        org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType result = org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType.forNumber(requestType_);
        return result == null ? org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.opensearch.extensions.proto.RequestType requestType = 1;</code>
       * @param value The requestType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestType(org.opensearch.extensions.proto.ExtensionRequestOuterClass.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.opensearch.extensions.proto.RequestType requestType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object uniqiueId_ = "";
      /**
       * <code>string uniqiueId = 2;</code>
       * @return The uniqiueId.
       */
      public java.lang.String getUniqiueId() {
        java.lang.Object ref = uniqiueId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uniqiueId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uniqiueId = 2;</code>
       * @return The bytes for uniqiueId.
       */
      public com.google.protobuf.ByteString
          getUniqiueIdBytes() {
        java.lang.Object ref = uniqiueId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uniqiueId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uniqiueId = 2;</code>
       * @param value The uniqiueId to set.
       * @return This builder for chaining.
       */
      public Builder setUniqiueId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uniqiueId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string uniqiueId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUniqiueId() {
        uniqiueId_ = getDefaultInstance().getUniqiueId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string uniqiueId = 2;</code>
       * @param value The bytes for uniqiueId to set.
       * @return This builder for chaining.
       */
      public Builder setUniqiueIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uniqiueId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.opensearch.extensions.proto.ExtensionRequest)
    }

    // @@protoc_insertion_point(class_scope:org.opensearch.extensions.proto.ExtensionRequest)
    private static final org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest();
    }

    public static org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExtensionRequest>
        PARSER = new com.google.protobuf.AbstractParser<ExtensionRequest>() {
      @java.lang.Override
      public ExtensionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ExtensionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExtensionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.opensearch.extensions.proto.ExtensionRequestOuterClass.ExtensionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_extensions_proto_ExtensionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_extensions_proto_ExtensionRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nKserver/src/main/java/org/opensearch/ex" +
      "tensions/proto/ExtensionRequest.proto\022\037o" +
      "rg.opensearch.extensions.proto\"h\n\020Extens" +
      "ionRequest\022A\n\013requestType\030\001 \001(\0162,.org.op" +
      "ensearch.extensions.proto.RequestType\022\021\n" +
      "\tuniqiueId\030\002 \001(\t*\307\002\n\013RequestType\022#\n\037REQU" +
      "EST_EXTENSION_CLUSTER_STATE\020\000\022&\n\"REQUEST" +
      "_EXTENSION_CLUSTER_SETTINGS\020\001\022+\n\'REQUEST" +
      "_EXTENSION_REGISTER_REST_ACTIONS\020\002\022\'\n#RE" +
      "QUEST_EXTENSION_REGISTER_SETTINGS\020\003\022*\n&R" +
      "EQUEST_EXTENSION_ENVIRONMENT_SETTINGS\020\004\022" +
      ",\n(REQUEST_EXTENSION_DEPENDENCY_INFORMAT" +
      "ION\020\005\022\024\n\020CREATE_COMPONENT\020\006\022\023\n\017ON_INDEX_" +
      "MODULE\020\007\022\020\n\014GET_SETTINGS\020\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_opensearch_extensions_proto_ExtensionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_opensearch_extensions_proto_ExtensionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_extensions_proto_ExtensionRequest_descriptor,
        new java.lang.String[] { "RequestType", "UniqiueId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
