### send request to create index
PUT http://localhost:9200/my-index
Content-Type: application/json

{
  "settings": {
    "ingestion_source": {
      "type": "kafka",
      "param": {
        "topic": "test1",
        "groupId": "test",
        "bootstrapServers": "localhost:49353"
      }
    },
    "index.number_of_shards": 1,
    "index.number_of_replicas": 1
  },
  "mappings": {
    "properties": {
      "name": {
        "type": "text"
      },
      "age": {
        "type": "integer"
      }
    }
  }
}


### query the index
GET http://localhost:9200/my-index/_search
Content-Type: application/json

{
  "query": {
    "range": {
      "age": {
        "gt": 18
      }
    }
  }
}
