name: "Branch Resolver"
description: "Select the appropriate branch for dependent repositories based on the current branch"
inputs:
  branch:
    description: "Branch to check"
    required: true
outputs:
  wazuh_indexer_plugins_branch:
    description: "Branch to use in wazuh-indexer-plugins repository."
    value: ${{ steps.resolve.outputs.wazuh_indexer_plugins_branch }}
  wazuh_indexer_reporting_branch:
    description: "Branch to use in wazuh-indexer-reporting repository."
    value: ${{ steps.resolve.outputs.wazuh_indexer_reporting_branch }}
  wazuh_indexer_security_analytics_branch:
    description: "Branch to use in wazuh-indexer-security-analytics repository."
    value: ${{ steps.resolve.outputs.wazuh_indexer_security_analytics_branch }}
  wazuh_indexer_notifications_branch:
    description: "Branch to use in wazuh-indexer-notifications repository."
    value: ${{ steps.resolve.outputs.wazuh_indexer_notifications_branch }}
  wazuh_indexer_common_utils_branch:
    description: "Branch to use in wazuh-indexer-common-utils repository."
    value: ${{ steps.resolve.outputs.wazuh_indexer_common_utils_branch }}
  wazuh_branch:
    description: "Branch to use in wazuh repository."
    value: ${{ steps.resolve.outputs.wazuh_branch }}
runs:
  using: "composite"
  steps:
    - id: resolve
      run: |
        wazuh_indexer_plugins_branch=""
        wazuh_indexer_reporting_branch=""
        wazuh_indexer_security_analytics_branch=""
        wazuh_indexer_notifications_branch=""
        wazuh_indexer_common_utils_branch=""
        wazuh_branch=""

        while IFS='=' read -r repo branch; do
          case "$repo" in
            wazuh-indexer-plugins)
              wazuh_indexer_plugins_branch="$branch"
              ;;
            wazuh-indexer-reporting)
              wazuh_indexer_reporting_branch="$branch"
              ;;
            wazuh-indexer-security-analytics)
              wazuh_indexer_security_analytics_branch="$branch"
              ;;
            wazuh-indexer-notifications)
              wazuh_indexer_notifications_branch="$branch"
              ;;
            wazuh-indexer-common-utils)
              wazuh_indexer_common_utils_branch="$branch"
              ;;
            wazuh)
              wazuh_branch="$branch"
              ;;
          esac
        done < <(${{ github.action_path }}/resolve_branches.sh "${{ inputs.branch }}")

        echo "wazuh_indexer_plugins_branch=$wazuh_indexer_plugins_branch" >> "$GITHUB_OUTPUT"
        echo "wazuh_indexer_reporting_branch=$wazuh_indexer_reporting_branch" >> "$GITHUB_OUTPUT"
        echo "wazuh_indexer_security_analytics_branch=$wazuh_indexer_security_analytics_branch" >> "$GITHUB_OUTPUT"
        echo "wazuh_indexer_notifications_branch=$wazuh_indexer_notifications_branch" >> "$GITHUB_OUTPUT"
        echo "wazuh_indexer_common_utils_branch=$wazuh_indexer_common_utils_branch" >> "$GITHUB_OUTPUT"
        echo "wazuh_branch=$wazuh_branch" >> "$GITHUB_OUTPUT"
      shell: bash
