services:
  # self-contained systemd example: run 'docker-compose up' to see it
  amazonlinux:
    image: opensearch-systemd-test
    container_name: opensearch-systemd-test-container
    build:
      dockerfile_inline: |
        FROM amazonlinux:2023
        # install systemd
        RUN dnf -y install systemd && dnf clean all
        # in practice, you'd COPY in the RPM you want to test right here
        RUN dnf -y install https://artifacts.opensearch.org/releases/bundle/opensearch/2.18.0/opensearch-2.18.0-linux-x64.rpm && dnf clean all
        # add a test-user
        RUN useradd -ms /bin/bash testuser
        # no colors
        ENV SYSTEMD_COLORS=0
        # no escapes
        ENV SYSTEMD_URLIFY=0
        # explicitly specify docker virtualization
        ENV container=docker
        # for debugging systemd issues in container, you want this, but it is very loud!
        # ENV SYSTEMD_LOG_LEVEL=debug
        # plumb journald logs to stdout
        COPY <<EOF /etc/systemd/journald.conf
        [Journal]
        ForwardToConsole=yes
        EOF
        # start systemd as PID 1
        CMD ["/sbin/init"]
        # enable opensearch service
        RUN systemctl enable opensearch
        # shutdown systemd properly
        STOPSIGNAL SIGRTMIN+3
        # disable security plugin, as i don't configure SSL (but could be done with openssl or whatever right here)
        RUN echo "plugins.security.disabled: true" >> /etc/opensearch/opensearch.yml
        RUN echo "network.host: 0.0.0.0" >> /etc/opensearch/opensearch.yml
        RUN echo "discovery.type: single-node" >> /etc/opensearch/opensearch.yml
    # provide /dev/console for journal logs to go to stdout
    tty: true
    # capabilities to allow systemd to sandbox
    cap_add:
      # https://systemd.io/CONTAINER_INTERFACE/#what-you-shouldnt-do bullet 1
      - SYS_ADMIN
      # https://systemd.io/CONTAINER_INTERFACE/#what-you-shouldnt-do bullet 2
      - MKNOD
    # evil, but best you can do on docker? podman is better here.
    cgroup: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ../../distribution/packages/src/common/systemd/opensearch.service:/etc/systemd/system/opensearch.service
    # tmpfs mounts for systemd
    tmpfs:
      - /run
      - /run/lock
    # health check for opensearch
    ports:
      - "9200:9200"
      - "9300:9300"
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      start_period: 15s