/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

package org.opensearch.index.engine;

import org.opensearch.index.seqno.SequenceNumbers;

import java.io.IOException;

/**
 * Test double for a plugin-supplied {@link PrimaryOperationPolicy} whose sequence numbers are
 * assigned by an upstream authority.
 */
class FakePreAssignedSeqNoPrimaryOperationPolicy implements PrimaryOperationPolicy {

    static final FakePreAssignedSeqNoPrimaryOperationPolicy INSTANCE = new FakePreAssignedSeqNoPrimaryOperationPolicy();

    private FakePreAssignedSeqNoPrimaryOperationPolicy() {}

    @Override
    public boolean acceptsPreAssignedSeqNos() {
        return true;
    }

    @Override
    public IndexingStrategy planIndex(OperationStrategyPlanner<Engine.Index, IndexingStrategy> planner, Engine.Index index)
        throws IOException {
        return planner.planOperationAsNonPrimary(asNonPrimary(index));
    }

    @Override
    public DeletionStrategy planDelete(OperationStrategyPlanner<Engine.Delete, DeletionStrategy> planner, Engine.Delete delete)
        throws IOException {
        return planner.planOperationAsNonPrimary(asNonPrimary(delete));
    }

    @Override
    public String toString() {
        return "fake-pre-assigned-seq-no";
    }

    /**
     * Re-tags an operation as {@link Engine.Operation.Origin#REPLICA} for planning only. The copy is
     * required rather than cosmetic: {@link IndexingStrategyPlanner} branches on origin when
     * deciding whether an append-only optimization applies, and the compare-and-swap fields are
     * dropped because the upstream authority already resolved them.
     */
    private static Engine.Index asNonPrimary(Engine.Index index) {
        return new Engine.Index(
            index.uid(),
            index.parsedDoc(),
            index.seqNo(),
            index.primaryTerm(),
            index.version(),
            null,
            Engine.Operation.Origin.REPLICA,
            index.startTime(),
            index.getAutoGeneratedIdTimestamp(),
            index.isRetry(),
            SequenceNumbers.UNASSIGNED_SEQ_NO,
            SequenceNumbers.UNASSIGNED_PRIMARY_TERM
        );
    }

    /** Delete counterpart of {@link #asNonPrimary(Engine.Index)}. */
    private static Engine.Delete asNonPrimary(Engine.Delete delete) {
        return new Engine.Delete(
            delete.id(),
            delete.uid(),
            delete.seqNo(),
            delete.primaryTerm(),
            delete.version(),
            null,
            Engine.Operation.Origin.REPLICA,
            delete.startTime(),
            SequenceNumbers.UNASSIGNED_SEQ_NO,
            SequenceNumbers.UNASSIGNED_PRIMARY_TERM,
            delete.routing()
        );
    }
}
