/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

package org.opensearch.index.engine.exec;

import org.opensearch.common.annotation.ExperimentalApi;
import org.opensearch.index.VersionType;
import org.opensearch.index.engine.Engine;
import org.opensearch.index.mapper.DocumentMapperForType;
import org.opensearch.index.mapper.SourceToParse;

import java.io.IOException;

/**
 * Core document operations for the indexer.
 * Defines the fundamental CRUD operations and history management for document indexing.
 *
 * @opensearch.experimental
 */
@ExperimentalApi
public interface IndexerEngineOperations {

    /**
     * Performs a document index operation.
     *
     * @param index the index operation containing document data and metadata
     * @return result containing updated translog location, version, and document-specific failures
     * @throws IOException if an I/O error occurs during indexing
     */
    Engine.IndexResult index(Engine.Index index) throws IOException;

    /**
     * Performs a document delete operation.
     *
     * @param delete the delete operation containing document identifier and metadata
     * @return result containing updated translog location, version, and document-specific failures
     * @throws IOException if an I/O error occurs during deletion
     */
    Engine.DeleteResult delete(Engine.Delete delete) throws IOException;

    /**
     * Performs a no-op operation for sequence number gap filling.
     * Used to maintain sequence number continuity in the translog.
     *
     * @param noOp the no-op operation
     * @return result of the no-op operation
     * @throws IOException if an I/O error occurs
     */
    Engine.NoOpResult noOp(Engine.NoOp noOp) throws IOException;

    /**
     * Prepares an index operation by parsing the source document and creating an Engine.Index operation.
     * This method validates and transforms the source into an executable index operation.
     *
     * @param docMapper the document mapper for field mapping and validation
     * @param source the source document to parse
     * @param seqNo the sequence number for this operation
     * @param primaryTerm the primary term
     * @param version the document version
     * @param versionType the version type for conflict resolution
     * @param origin the operation origin (primary, replica, local, peer recovery)
     * @param autoGeneratedIdTimestamp timestamp for auto-generated document IDs
     * @param isRetry whether this is a retry of a previous operation
     * @param ifSeqNo conditional sequence number for optimistic concurrency control
     * @param ifPrimaryTerm conditional primary term for optimistic concurrency control
     * @return the prepared index operation ready for execution
     */
    Engine.Index prepareIndex(
        DocumentMapperForType docMapper,
        SourceToParse source,
        long seqNo,
        long primaryTerm,
        long version,
        VersionType versionType,
        Engine.Operation.Origin origin,
        long autoGeneratedIdTimestamp,
        boolean isRetry,
        long ifSeqNo,
        long ifPrimaryTerm
    );

    /**
     * Prepares a delete operation by creating an Engine.Delete operation.
     *
     * @param id the document identifier
     * @param seqNo the sequence number for this operation
     * @param primaryTerm the primary term
     * @param version the document version
     * @param versionType the version type for conflict resolution
     * @param origin the operation origin (primary, replica, local, peer recovery)
     * @param ifSeqNo conditional sequence number for optimistic concurrency control
     * @param ifPrimaryTerm conditional primary term for optimistic concurrency control
     * @return the prepared delete operation ready for execution
     */
    Engine.Delete prepareDelete(
        String id,
        long seqNo,
        long primaryTerm,
        long version,
        VersionType versionType,
        Engine.Operation.Origin origin,
        long ifSeqNo,
        long ifPrimaryTerm
    );
}
