[[es-tmpdir]]
[discrete]
=== Temporary directory settings

By default, {opensearch} uses a private temporary directory that the startup
script creates immediately below the system temporary directory.

On some Linux distributions, a system utility will clean files and directories
from `/tmp` if they have not been recently accessed. This behavior can lead to
the private temporary directory being removed while {opensearch} is running if
features that require the temporary directory are not used for a long time.
Removing the private temporary directory causes problems if a feature that
requires this directory is subsequently used.

If you install {opensearch} using the `.deb` or `.rpm` packages and run it
under `systemd`, the private temporary directory that {opensearch} uses
is excluded from periodic cleanup.

If you intend to run the `.tar.gz` distribution on Linux or MacOS for
an extended period, consider creating a dedicated temporary
directory for {opensearch} that is not under a path that will have old files
and directories cleaned from it. This directory should have permissions set
so that only the user that {opensearch} runs as can access it. Then, set the
`$OPENSEARCH_TMPDIR` environment variable to point to this directory before starting
{opensearch}.
