/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

package org.opensearch.action.admin.cluster.catalog;

import org.opensearch.action.support.broadcast.BroadcastRequest;
import org.opensearch.core.common.io.stream.StreamInput;
import org.opensearch.core.common.io.stream.StreamOutput;

import java.io.IOException;
import java.util.Objects;

/**
 * Request to publish shard data to the catalog registered on each node. Carries the
 * index name plus a per-publish correlation id generated by the orchestrator. There is
 * one catalog destination per node, configured via node settings at startup, so the
 * request does not include any repository identity.
 *
 * @opensearch.experimental
 */
public class PublishShardRequest extends BroadcastRequest<PublishShardRequest> {

    private final String publishId;

    /**
     * Creates a new request for the given index under the given publish correlation id.
     *
     * @param publishId unique id assigned by {@link org.opensearch.catalog.RemoteCatalogService}
     *                  to correlate all shard invocations of one logical publish. The
     *                  id is threaded down to {@code CatalogMetadataClient.copyShard}.
     * @param indexName index to publish
     */
    public PublishShardRequest(String publishId, String indexName) {
        super(indexName);
        this.publishId = Objects.requireNonNull(publishId, "publishId must not be null");
    }

    public PublishShardRequest(StreamInput in) throws IOException {
        super(in);
        this.publishId = in.readString();
    }

    /** Returns the correlation id for this publish. Never {@code null}. */
    public String getPublishId() {
        return publishId;
    }

    @Override
    public void writeTo(StreamOutput out) throws IOException {
        super.writeTo(out);
        out.writeString(publishId);
    }

    @Override
    public String toString() {
        return "PublishShardRequest{publishId=" + publishId + ",indices=" + String.join(",", indices()) + "}";
    }
}
