[[analysis-smartcn]]
=== Smart Chinese Analysis Plugin

The Smart Chinese Analysis plugin integrates Lucene's Smart Chinese analysis
module into opensearch.

It provides an analyzer for Chinese or mixed Chinese-English text. This
analyzer uses probabilistic knowledge to find the optimal word segmentation
for Simplified Chinese text. The text is first broken into sentences, then
each sentence is segmented into words.

:plugin_name: analysis-smartcn
include::install_remove.asciidoc[]


[[analysis-smartcn-tokenizer]]
[discrete]
==== `smartcn` tokenizer and token filter

The plugin provides the `smartcn` analyzer, `smartcn_tokenizer` tokenizer, and
`smartcn_stop` token filter which are not configurable.

NOTE: The `smartcn_word` token filter and `smartcn_sentence` have been deprecated.

==== Reimplementing and extending the analyzers

The `smartcn` analyzer could be reimplemented as a `custom` analyzer that can
then be extended and configured as follows:

[source,console]
----------------------------------------------------
PUT smartcn_example
{
  "settings": {
    "analysis": {
      "analyzer": {
        "rebuilt_smartcn": {
          "tokenizer":  "smartcn_tokenizer",
          "filter": [
            "porter_stem",
            "smartcn_stop"
          ]
        }
      }
    }
  }
}
----------------------------------------------------
// TEST[s/\n$/\nstartyaml\n  - compare_analyzers: {index: smartcn_example, first: smartcn, second: rebuilt_smartcn}\nendyaml\n/]

[[analysis-smartcn_stop]]
==== `smartcn_stop` token filter

The `smartcn_stop` token filter filters out stopwords defined by `smartcn`
analyzer (`_smartcn_`), and any other custom stopwords specified by the user.
This filter only supports the predefined `_smartcn_` stopwords list.
If you want to use a different predefined list, then use the
{ref}/analysis-stop-tokenfilter.html[`stop` token filter] instead.

// TODO(OpenSearch): Replace the example
[source,console]
--------------------------------------------------
PUT smartcn_example
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "smartcn_with_stop": {
            "tokenizer": "smartcn_tokenizer",
            "filter": [
              "porter_stem",
              "my_smartcn_stop"
            ]
          }
        },
        "filter": {
          "my_smartcn_stop": {
            "type": "smartcn_stop",
            "stopwords": [
              "_smartcn_",
              "project",
              "的"
            ]
          }
        }
      }
    }
  }
}

GET smartcn_example/_analyze
{
  "analyzer": "smartcn_with_stop",
  "text": "哈喽，我们是 OpenSearch Project（OpenSearch 和 OpenSearch Dashboards）的开发者。从股票行情到 Twitter 消息流，从 Apache 日志到 WordPress 博文，我们可以帮助人们体验搜索的强大力量，帮助他们以截然不同的方式探索和分析数据"
}
--------------------------------------------------

The above request returns:

[source,console-result]
--------------------------------------------------
{
  "tokens": [
    {
      "token": "哈",
      "start_offset": 0,
      "end_offset": 1,
      "type": "word",
      "position": 0
    },
    {
      "token": "喽",
      "start_offset": 1,
      "end_offset": 2,
      "type": "word",
      "position": 1
    },
    {
      "token": "我们",
      "start_offset": 3,
      "end_offset": 5,
      "type": "word",
      "position": 3
    },
    {
      "token": "是",
      "start_offset": 5,
      "end_offset": 6,
      "type": "word",
      "position": 4
    },
    {
      "token": "opensearch",
      "start_offset": 7,
      "end_offset": 17,
      "type": "word",
      "position": 5
    },
    {
      "token": "opensearch",
      "start_offset": 26,
      "end_offset": 36,
      "type": "word",
      "position": 8
    },
    {
      "token": "和",
      "start_offset": 37,
      "end_offset": 38,
      "type": "word",
      "position": 9
    },
    {
      "token": "opensearch",
      "start_offset": 39,
      "end_offset": 49,
      "type": "word",
      "position": 10
    },
    {
      "token": "dashboard",
      "start_offset": 50,
      "end_offset": 60,
      "type": "word",
      "position": 11
    },
    {
      "token": "开发",
      "start_offset": 62,
      "end_offset": 64,
      "type": "word",
      "position": 14
    },
    {
      "token": "者",
      "start_offset": 64,
      "end_offset": 65,
      "type": "word",
      "position": 15
    },
    {
      "token": "从",
      "start_offset": 66,
      "end_offset": 67,
      "type": "word",
      "position": 17
    },
    {
      "token": "股票",
      "start_offset": 67,
      "end_offset": 69,
      "type": "word",
      "position": 18
    },
    {
      "token": "行情",
      "start_offset": 69,
      "end_offset": 71,
      "type": "word",
      "position": 19
    },
    {
      "token": "到",
      "start_offset": 71,
      "end_offset": 72,
      "type": "word",
      "position": 20
    },
    {
      "token": "twitter",
      "start_offset": 73,
      "end_offset": 80,
      "type": "word",
      "position": 21
    },
    {
      "token": "消息",
      "start_offset": 81,
      "end_offset": 83,
      "type": "word",
      "position": 22
    },
    {
      "token": "流",
      "start_offset": 83,
      "end_offset": 84,
      "type": "word",
      "position": 23
    },
    {
      "token": "从",
      "start_offset": 85,
      "end_offset": 86,
      "type": "word",
      "position": 25
    },
    {
      "token": "apach",
      "start_offset": 87,
      "end_offset": 93,
      "type": "word",
      "position": 26
    },
    {
      "token": "日志",
      "start_offset": 94,
      "end_offset": 96,
      "type": "word",
      "position": 27
    },
    {
      "token": "到",
      "start_offset": 96,
      "end_offset": 97,
      "type": "word",
      "position": 28
    },
    {
      "token": "wordpress",
      "start_offset": 98,
      "end_offset": 107,
      "type": "word",
      "position": 29
    },
    {
      "token": "博",
      "start_offset": 108,
      "end_offset": 109,
      "type": "word",
      "position": 30
    },
    {
      "token": "文",
      "start_offset": 109,
      "end_offset": 110,
      "type": "word",
      "position": 31
    },
    {
      "token": "我们",
      "start_offset": 111,
      "end_offset": 113,
      "type": "word",
      "position": 33
    },
    {
      "token": "可以",
      "start_offset": 113,
      "end_offset": 115,
      "type": "word",
      "position": 34
    },
    {
      "token": "帮助",
      "start_offset": 115,
      "end_offset": 117,
      "type": "word",
      "position": 35
    },
    {
      "token": "人们",
      "start_offset": 117,
      "end_offset": 119,
      "type": "word",
      "position": 36
    },
    {
      "token": "体验",
      "start_offset": 119,
      "end_offset": 121,
      "type": "word",
      "position": 37
    },
    {
      "token": "搜索",
      "start_offset": 121,
      "end_offset": 123,
      "type": "word",
      "position": 38
    },
    {
      "token": "强大",
      "start_offset": 124,
      "end_offset": 126,
      "type": "word",
      "position": 40
    },
    {
      "token": "力量",
      "start_offset": 126,
      "end_offset": 128,
      "type": "word",
      "position": 41
    },
    {
      "token": "帮助",
      "start_offset": 129,
      "end_offset": 131,
      "type": "word",
      "position": 43
    },
    {
      "token": "他们",
      "start_offset": 131,
      "end_offset": 133,
      "type": "word",
      "position": 44
    },
    {
      "token": "以",
      "start_offset": 133,
      "end_offset": 134,
      "type": "word",
      "position": 45
    },
    {
      "token": "截然不同",
      "start_offset": 134,
      "end_offset": 138,
      "type": "word",
      "position": 46
    },
    {
      "token": "方式",
      "start_offset": 139,
      "end_offset": 141,
      "type": "word",
      "position": 48
    },
    {
      "token": "探索",
      "start_offset": 141,
      "end_offset": 143,
      "type": "word",
      "position": 49
    },
    {
      "token": "和",
      "start_offset": 143,
      "end_offset": 144,
      "type": "word",
      "position": 50
    },
    {
      "token": "分析",
      "start_offset": 144,
      "end_offset": 146,
      "type": "word",
      "position": 51
    },
    {
      "token": "数据",
      "start_offset": 146,
      "end_offset": 148,
      "type": "word",
      "position": 52
    }
  ]
}
--------------------------------------------------
