/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.opensearch.plugin.hive.metastore;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked", "unused" })
public class GetTableRequest
    implements
        org.apache.thrift.TBase<GetTableRequest, GetTableRequest._Fields>,
        java.io.Serializable,
        Cloneable,
        Comparable<GetTableRequest> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetTableRequest");

    private static final org.apache.thrift.protocol.TField DB_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "dbName",
        org.apache.thrift.protocol.TType.STRING,
        (short) 1
    );
    private static final org.apache.thrift.protocol.TField TBL_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "tblName",
        org.apache.thrift.protocol.TType.STRING,
        (short) 2
    );

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new GetTableRequestStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new GetTableRequestTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable java.lang.String dbName; // required
    public @org.apache.thrift.annotation.Nullable java.lang.String tblName; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        DB_NAME((short) 1, "dbName"),
        TBL_NAME((short) 2, "tblName");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // DB_NAME
                    return DB_NAME;
                case 2: // TBL_NAME
                    return TBL_NAME;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId() {
            return _thriftId;
        }

        @Override
        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<
            _Fields,
            org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(
            _Fields.DB_NAME,
            new org.apache.thrift.meta_data.FieldMetaData(
                "dbName",
                org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)
            )
        );
        tmpMap.put(
            _Fields.TBL_NAME,
            new org.apache.thrift.meta_data.FieldMetaData(
                "tblName",
                org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)
            )
        );
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetTableRequest.class, metaDataMap);
    }

    public GetTableRequest() {}

    public GetTableRequest(java.lang.String dbName, java.lang.String tblName) {
        this();
        this.dbName = dbName;
        this.tblName = tblName;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public GetTableRequest(GetTableRequest other) {
        if (other.isSetDbName()) {
            this.dbName = other.dbName;
        }
        if (other.isSetTblName()) {
            this.tblName = other.tblName;
        }
    }

    @Override
    public GetTableRequest deepCopy() {
        return new GetTableRequest(this);
    }

    @Override
    public void clear() {
        this.dbName = null;
        this.tblName = null;
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getDbName() {
        return this.dbName;
    }

    public GetTableRequest setDbName(@org.apache.thrift.annotation.Nullable java.lang.String dbName) {
        this.dbName = dbName;
        return this;
    }

    public void unsetDbName() {
        this.dbName = null;
    }

    /** Returns true if field dbName is set (has been assigned a value) and false otherwise */
    public boolean isSetDbName() {
        return this.dbName != null;
    }

    public void setDbNameIsSet(boolean value) {
        if (!value) {
            this.dbName = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getTblName() {
        return this.tblName;
    }

    public GetTableRequest setTblName(@org.apache.thrift.annotation.Nullable java.lang.String tblName) {
        this.tblName = tblName;
        return this;
    }

    public void unsetTblName() {
        this.tblName = null;
    }

    /** Returns true if field tblName is set (has been assigned a value) and false otherwise */
    public boolean isSetTblName() {
        return this.tblName != null;
    }

    public void setTblNameIsSet(boolean value) {
        if (!value) {
            this.tblName = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case DB_NAME:
                if (value == null) {
                    unsetDbName();
                } else {
                    setDbName((java.lang.String) value);
                }
                break;

            case TBL_NAME:
                if (value == null) {
                    unsetTblName();
                } else {
                    setTblName((java.lang.String) value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case DB_NAME:
                return getDbName();

            case TBL_NAME:
                return getTblName();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case DB_NAME:
                return isSetDbName();
            case TBL_NAME:
                return isSetTblName();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that instanceof GetTableRequest) return this.equals((GetTableRequest) that);
        return false;
    }

    public boolean equals(GetTableRequest that) {
        if (that == null) return false;
        if (this == that) return true;

        boolean this_present_dbName = true && this.isSetDbName();
        boolean that_present_dbName = true && that.isSetDbName();
        if (this_present_dbName || that_present_dbName) {
            if (!(this_present_dbName && that_present_dbName)) return false;
            if (!this.dbName.equals(that.dbName)) return false;
        }

        boolean this_present_tblName = true && this.isSetTblName();
        boolean that_present_tblName = true && that.isSetTblName();
        if (this_present_tblName || that_present_tblName) {
            if (!(this_present_tblName && that_present_tblName)) return false;
            if (!this.tblName.equals(that.tblName)) return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetDbName()) ? 131071 : 524287);
        if (isSetDbName()) hashCode = hashCode * 8191 + dbName.hashCode();

        hashCode = hashCode * 8191 + ((isSetTblName()) ? 131071 : 524287);
        if (isSetTblName()) hashCode = hashCode * 8191 + tblName.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(GetTableRequest other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.compare(isSetDbName(), other.isSetDbName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetDbName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dbName, other.dbName);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetTblName(), other.isSetTblName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTblName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tblName, other.tblName);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("GetTableRequest(");
        boolean first = true;

        sb.append("dbName:");
        if (this.dbName == null) {
            sb.append("null");
        } else {
            sb.append(this.dbName);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("tblName:");
        if (this.tblName == null) {
            sb.append("null");
        } else {
            sb.append(this.tblName);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        if (dbName == null) {
            throw new org.apache.thrift.protocol.TProtocolException("Required field 'dbName' was not present! Struct: " + toString());
        }
        if (tblName == null) {
            throw new org.apache.thrift.protocol.TProtocolException("Required field 'tblName' was not present! Struct: " + toString());
        }
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class GetTableRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public GetTableRequestStandardScheme getScheme() {
            return new GetTableRequestStandardScheme();
        }
    }

    private static class GetTableRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<GetTableRequest> {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, GetTableRequest struct) throws org.apache.thrift.TException {
            iprot.incrementRecursionDepth();
            try {
                org.apache.thrift.protocol.TField schemeField;
                iprot.readStructBegin();
                while (true) {
                    schemeField = iprot.readFieldBegin();
                    if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                        break;
                    }
                    switch (schemeField.id) {
                        case 1: // DB_NAME
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                                struct.dbName = iprot.readString();
                                struct.setDbNameIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        case 2: // TBL_NAME
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                                struct.tblName = iprot.readString();
                                struct.setTblNameIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        default:
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                    }
                    iprot.readFieldEnd();
                }
                iprot.readStructEnd();

                // check for required fields of primitive type, which can't be checked in the validate method
                struct.validate();
            } finally {
                iprot.decrementRecursionDepth();
            }
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, GetTableRequest struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.dbName != null) {
                oprot.writeFieldBegin(DB_NAME_FIELD_DESC);
                oprot.writeString(struct.dbName);
                oprot.writeFieldEnd();
            }
            if (struct.tblName != null) {
                oprot.writeFieldBegin(TBL_NAME_FIELD_DESC);
                oprot.writeString(struct.tblName);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class GetTableRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public GetTableRequestTupleScheme getScheme() {
            return new GetTableRequestTupleScheme();
        }
    }

    private static class GetTableRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<GetTableRequest> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, GetTableRequest struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            oprot.writeString(struct.dbName);
            oprot.writeString(struct.tblName);
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, GetTableRequest struct) throws org.apache.thrift.TException {
            prot.incrementRecursionDepth();
            try {
                org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
                struct.dbName = iprot.readString();
                struct.setDbNameIsSet(true);
                struct.tblName = iprot.readString();
                struct.setTblNameIsSet(true);
            } finally {
                prot.decrementRecursionDepth();
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY)
            .getScheme();
    }
}
