/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.opensearch.plugin.hive.metastore;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked", "unused" })
public class GetTableResult
    implements
        org.apache.thrift.TBase<GetTableResult, GetTableResult._Fields>,
        java.io.Serializable,
        Cloneable,
        Comparable<GetTableResult> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetTableResult");

    private static final org.apache.thrift.protocol.TField TABLE_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "table",
        org.apache.thrift.protocol.TType.STRUCT,
        (short) 1
    );

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new GetTableResultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new GetTableResultTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable Table table; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        TABLE((short) 1, "table");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // TABLE
                    return TABLE;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId() {
            return _thriftId;
        }

        @Override
        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<
            _Fields,
            org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(
            _Fields.TABLE,
            new org.apache.thrift.meta_data.FieldMetaData(
                "table",
                org.apache.thrift.TFieldRequirementType.REQUIRED,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Table.class)
            )
        );
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetTableResult.class, metaDataMap);
    }

    public GetTableResult() {}

    public GetTableResult(Table table) {
        this();
        this.table = table;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public GetTableResult(GetTableResult other) {
        if (other.isSetTable()) {
            this.table = new Table(other.table);
        }
    }

    @Override
    public GetTableResult deepCopy() {
        return new GetTableResult(this);
    }

    @Override
    public void clear() {
        this.table = null;
    }

    @org.apache.thrift.annotation.Nullable
    public Table getTable() {
        return this.table;
    }

    public GetTableResult setTable(@org.apache.thrift.annotation.Nullable Table table) {
        this.table = table;
        return this;
    }

    public void unsetTable() {
        this.table = null;
    }

    /** Returns true if field table is set (has been assigned a value) and false otherwise */
    public boolean isSetTable() {
        return this.table != null;
    }

    public void setTableIsSet(boolean value) {
        if (!value) {
            this.table = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case TABLE:
                if (value == null) {
                    unsetTable();
                } else {
                    setTable((Table) value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case TABLE:
                return getTable();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case TABLE:
                return isSetTable();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that instanceof GetTableResult) return this.equals((GetTableResult) that);
        return false;
    }

    public boolean equals(GetTableResult that) {
        if (that == null) return false;
        if (this == that) return true;

        boolean this_present_table = true && this.isSetTable();
        boolean that_present_table = true && that.isSetTable();
        if (this_present_table || that_present_table) {
            if (!(this_present_table && that_present_table)) return false;
            if (!this.table.equals(that.table)) return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetTable()) ? 131071 : 524287);
        if (isSetTable()) hashCode = hashCode * 8191 + table.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(GetTableResult other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.compare(isSetTable(), other.isSetTable());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTable()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.table, other.table);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("GetTableResult(");
        boolean first = true;

        sb.append("table:");
        if (this.table == null) {
            sb.append("null");
        } else {
            sb.append(this.table);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        if (table == null) {
            throw new org.apache.thrift.protocol.TProtocolException("Required field 'table' was not present! Struct: " + toString());
        }
        // check for sub-struct validity
        if (table != null) {
            table.validate();
        }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class GetTableResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public GetTableResultStandardScheme getScheme() {
            return new GetTableResultStandardScheme();
        }
    }

    private static class GetTableResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<GetTableResult> {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, GetTableResult struct) throws org.apache.thrift.TException {
            iprot.incrementRecursionDepth();
            try {
                org.apache.thrift.protocol.TField schemeField;
                iprot.readStructBegin();
                while (true) {
                    schemeField = iprot.readFieldBegin();
                    if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                        break;
                    }
                    switch (schemeField.id) {
                        case 1: // TABLE
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                                struct.table = new Table();
                                struct.table.read(iprot);
                                struct.setTableIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        default:
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                    }
                    iprot.readFieldEnd();
                }
                iprot.readStructEnd();

                // check for required fields of primitive type, which can't be checked in the validate method
                struct.validate();
            } finally {
                iprot.decrementRecursionDepth();
            }
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, GetTableResult struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.table != null) {
                oprot.writeFieldBegin(TABLE_FIELD_DESC);
                struct.table.write(oprot);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class GetTableResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public GetTableResultTupleScheme getScheme() {
            return new GetTableResultTupleScheme();
        }
    }

    private static class GetTableResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<GetTableResult> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, GetTableResult struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            struct.table.write(oprot);
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, GetTableResult struct) throws org.apache.thrift.TException {
            prot.incrementRecursionDepth();
            try {
                org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
                struct.table = new Table();
                struct.table.read(iprot);
                struct.setTableIsSet(true);
            } finally {
                prot.decrementRecursionDepth();
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY)
            .getScheme();
    }
}
