/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.opensearch.plugin.hive.metastore;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked", "unused" })
public class Order implements org.apache.thrift.TBase<Order, Order._Fields>, java.io.Serializable, Cloneable, Comparable<Order> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Order");

    private static final org.apache.thrift.protocol.TField COL_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "col",
        org.apache.thrift.protocol.TType.STRING,
        (short) 1
    );
    private static final org.apache.thrift.protocol.TField ORDER_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "order",
        org.apache.thrift.protocol.TType.I32,
        (short) 2
    );

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new OrderStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new OrderTupleSchemeFactory();

    private @org.apache.thrift.annotation.Nullable java.lang.String col; // required
    private int order; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        COL((short) 1, "col"),
        ORDER((short) 2, "order");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // COL
                    return COL;
                case 2: // ORDER
                    return ORDER;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId() {
            return _thriftId;
        }

        @Override
        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __ORDER_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<
            _Fields,
            org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(
            _Fields.COL,
            new org.apache.thrift.meta_data.FieldMetaData(
                "col",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)
            )
        );
        tmpMap.put(
            _Fields.ORDER,
            new org.apache.thrift.meta_data.FieldMetaData(
                "order",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)
            )
        );
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Order.class, metaDataMap);
    }

    public Order() {}

    public Order(java.lang.String col, int order) {
        this();
        this.col = col;
        this.order = order;
        setOrderIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public Order(Order other) {
        __isset_bitfield = other.__isset_bitfield;
        if (other.isSetCol()) {
            this.col = other.col;
        }
        this.order = other.order;
    }

    @Override
    public Order deepCopy() {
        return new Order(this);
    }

    @Override
    public void clear() {
        this.col = null;
        setOrderIsSet(false);
        this.order = 0;
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getCol() {
        return this.col;
    }

    public Order setCol(@org.apache.thrift.annotation.Nullable java.lang.String col) {
        this.col = col;
        return this;
    }

    public void unsetCol() {
        this.col = null;
    }

    /** Returns true if field col is set (has been assigned a value) and false otherwise */
    public boolean isSetCol() {
        return this.col != null;
    }

    public void setColIsSet(boolean value) {
        if (!value) {
            this.col = null;
        }
    }

    public int getOrder() {
        return this.order;
    }

    public Order setOrder(int order) {
        this.order = order;
        setOrderIsSet(true);
        return this;
    }

    public void unsetOrder() {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ORDER_ISSET_ID);
    }

    /** Returns true if field order is set (has been assigned a value) and false otherwise */
    public boolean isSetOrder() {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ORDER_ISSET_ID);
    }

    public void setOrderIsSet(boolean value) {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ORDER_ISSET_ID, value);
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case COL:
                if (value == null) {
                    unsetCol();
                } else {
                    setCol((java.lang.String) value);
                }
                break;

            case ORDER:
                if (value == null) {
                    unsetOrder();
                } else {
                    setOrder((java.lang.Integer) value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case COL:
                return getCol();

            case ORDER:
                return getOrder();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case COL:
                return isSetCol();
            case ORDER:
                return isSetOrder();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that instanceof Order) return this.equals((Order) that);
        return false;
    }

    public boolean equals(Order that) {
        if (that == null) return false;
        if (this == that) return true;

        boolean this_present_col = true && this.isSetCol();
        boolean that_present_col = true && that.isSetCol();
        if (this_present_col || that_present_col) {
            if (!(this_present_col && that_present_col)) return false;
            if (!this.col.equals(that.col)) return false;
        }

        boolean this_present_order = true;
        boolean that_present_order = true;
        if (this_present_order || that_present_order) {
            if (!(this_present_order && that_present_order)) return false;
            if (this.order != that.order) return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetCol()) ? 131071 : 524287);
        if (isSetCol()) hashCode = hashCode * 8191 + col.hashCode();

        hashCode = hashCode * 8191 + order;

        return hashCode;
    }

    @Override
    public int compareTo(Order other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.compare(isSetCol(), other.isSetCol());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetCol()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.col, other.col);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetOrder(), other.isSetOrder());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetOrder()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.order, other.order);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("Order(");
        boolean first = true;

        sb.append("col:");
        if (this.col == null) {
            sb.append("null");
        } else {
            sb.append(this.col);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("order:");
        sb.append(this.order);
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class OrderStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public OrderStandardScheme getScheme() {
            return new OrderStandardScheme();
        }
    }

    private static class OrderStandardScheme extends org.apache.thrift.scheme.StandardScheme<Order> {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, Order struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // COL
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.col = iprot.readString();
                            struct.setColIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // ORDER
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.order = iprot.readI32();
                            struct.setOrderIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, Order struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.col != null) {
                oprot.writeFieldBegin(COL_FIELD_DESC);
                oprot.writeString(struct.col);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(ORDER_FIELD_DESC);
            oprot.writeI32(struct.order);
            oprot.writeFieldEnd();
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class OrderTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public OrderTupleScheme getScheme() {
            return new OrderTupleScheme();
        }
    }

    private static class OrderTupleScheme extends org.apache.thrift.scheme.TupleScheme<Order> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, Order struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetCol()) {
                optionals.set(0);
            }
            if (struct.isSetOrder()) {
                optionals.set(1);
            }
            oprot.writeBitSet(optionals, 2);
            if (struct.isSetCol()) {
                oprot.writeString(struct.col);
            }
            if (struct.isSetOrder()) {
                oprot.writeI32(struct.order);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, Order struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(2);
            if (incoming.get(0)) {
                struct.col = iprot.readString();
                struct.setColIsSet(true);
            }
            if (incoming.get(1)) {
                struct.order = iprot.readI32();
                struct.setOrderIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY)
            .getScheme();
    }
}
