/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.opensearch.plugin.hive.metastore;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked", "unused" })
public class PrincipalPrivilegeSet
    implements
        org.apache.thrift.TBase<PrincipalPrivilegeSet, PrincipalPrivilegeSet._Fields>,
        java.io.Serializable,
        Cloneable,
        Comparable<PrincipalPrivilegeSet> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PrincipalPrivilegeSet");

    private static final org.apache.thrift.protocol.TField USER_PRIVILEGES_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "userPrivileges",
        org.apache.thrift.protocol.TType.MAP,
        (short) 1
    );
    private static final org.apache.thrift.protocol.TField GROUP_PRIVILEGES_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "groupPrivileges",
        org.apache.thrift.protocol.TType.MAP,
        (short) 2
    );
    private static final org.apache.thrift.protocol.TField ROLE_PRIVILEGES_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "rolePrivileges",
        org.apache.thrift.protocol.TType.MAP,
        (short) 3
    );

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PrincipalPrivilegeSetStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PrincipalPrivilegeSetTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> userPrivileges; // required
    public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> groupPrivileges; // required
    public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> rolePrivileges; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        USER_PRIVILEGES((short) 1, "userPrivileges"),
        GROUP_PRIVILEGES((short) 2, "groupPrivileges"),
        ROLE_PRIVILEGES((short) 3, "rolePrivileges");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // USER_PRIVILEGES
                    return USER_PRIVILEGES;
                case 2: // GROUP_PRIVILEGES
                    return GROUP_PRIVILEGES;
                case 3: // ROLE_PRIVILEGES
                    return ROLE_PRIVILEGES;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId() {
            return _thriftId;
        }

        @Override
        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<
            _Fields,
            org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(
            _Fields.USER_PRIVILEGES,
            new org.apache.thrift.meta_data.FieldMetaData(
                "userPrivileges",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.MapMetaData(
                    org.apache.thrift.protocol.TType.MAP,
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
                    new org.apache.thrift.meta_data.ListMetaData(
                        org.apache.thrift.protocol.TType.LIST,
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PrivilegeGrantInfo.class)
                    )
                )
            )
        );
        tmpMap.put(
            _Fields.GROUP_PRIVILEGES,
            new org.apache.thrift.meta_data.FieldMetaData(
                "groupPrivileges",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.MapMetaData(
                    org.apache.thrift.protocol.TType.MAP,
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
                    new org.apache.thrift.meta_data.ListMetaData(
                        org.apache.thrift.protocol.TType.LIST,
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PrivilegeGrantInfo.class)
                    )
                )
            )
        );
        tmpMap.put(
            _Fields.ROLE_PRIVILEGES,
            new org.apache.thrift.meta_data.FieldMetaData(
                "rolePrivileges",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.MapMetaData(
                    org.apache.thrift.protocol.TType.MAP,
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
                    new org.apache.thrift.meta_data.ListMetaData(
                        org.apache.thrift.protocol.TType.LIST,
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PrivilegeGrantInfo.class)
                    )
                )
            )
        );
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PrincipalPrivilegeSet.class, metaDataMap);
    }

    public PrincipalPrivilegeSet() {}

    public PrincipalPrivilegeSet(
        java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> userPrivileges,
        java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> groupPrivileges,
        java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> rolePrivileges
    ) {
        this();
        this.userPrivileges = userPrivileges;
        this.groupPrivileges = groupPrivileges;
        this.rolePrivileges = rolePrivileges;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public PrincipalPrivilegeSet(PrincipalPrivilegeSet other) {
        if (other.isSetUserPrivileges()) {
            java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> __this__userPrivileges = new java.util.HashMap<
                java.lang.String,
                java.util.List<PrivilegeGrantInfo>>(other.userPrivileges.size());
            for (java.util.Map.Entry<java.lang.String, java.util.List<PrivilegeGrantInfo>> other_element : other.userPrivileges
                .entrySet()) {

                java.lang.String other_element_key = other_element.getKey();
                java.util.List<PrivilegeGrantInfo> other_element_value = other_element.getValue();

                java.lang.String __this__userPrivileges_copy_key = other_element_key;

                java.util.List<PrivilegeGrantInfo> __this__userPrivileges_copy_value = new java.util.ArrayList<PrivilegeGrantInfo>(
                    other_element_value.size()
                );
                for (PrivilegeGrantInfo other_element_value_element : other_element_value) {
                    __this__userPrivileges_copy_value.add(new PrivilegeGrantInfo(other_element_value_element));
                }

                __this__userPrivileges.put(__this__userPrivileges_copy_key, __this__userPrivileges_copy_value);
            }
            this.userPrivileges = __this__userPrivileges;
        }
        if (other.isSetGroupPrivileges()) {
            java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> __this__groupPrivileges = new java.util.HashMap<
                java.lang.String,
                java.util.List<PrivilegeGrantInfo>>(other.groupPrivileges.size());
            for (java.util.Map.Entry<java.lang.String, java.util.List<PrivilegeGrantInfo>> other_element : other.groupPrivileges
                .entrySet()) {

                java.lang.String other_element_key = other_element.getKey();
                java.util.List<PrivilegeGrantInfo> other_element_value = other_element.getValue();

                java.lang.String __this__groupPrivileges_copy_key = other_element_key;

                java.util.List<PrivilegeGrantInfo> __this__groupPrivileges_copy_value = new java.util.ArrayList<PrivilegeGrantInfo>(
                    other_element_value.size()
                );
                for (PrivilegeGrantInfo other_element_value_element : other_element_value) {
                    __this__groupPrivileges_copy_value.add(new PrivilegeGrantInfo(other_element_value_element));
                }

                __this__groupPrivileges.put(__this__groupPrivileges_copy_key, __this__groupPrivileges_copy_value);
            }
            this.groupPrivileges = __this__groupPrivileges;
        }
        if (other.isSetRolePrivileges()) {
            java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> __this__rolePrivileges = new java.util.HashMap<
                java.lang.String,
                java.util.List<PrivilegeGrantInfo>>(other.rolePrivileges.size());
            for (java.util.Map.Entry<java.lang.String, java.util.List<PrivilegeGrantInfo>> other_element : other.rolePrivileges
                .entrySet()) {

                java.lang.String other_element_key = other_element.getKey();
                java.util.List<PrivilegeGrantInfo> other_element_value = other_element.getValue();

                java.lang.String __this__rolePrivileges_copy_key = other_element_key;

                java.util.List<PrivilegeGrantInfo> __this__rolePrivileges_copy_value = new java.util.ArrayList<PrivilegeGrantInfo>(
                    other_element_value.size()
                );
                for (PrivilegeGrantInfo other_element_value_element : other_element_value) {
                    __this__rolePrivileges_copy_value.add(new PrivilegeGrantInfo(other_element_value_element));
                }

                __this__rolePrivileges.put(__this__rolePrivileges_copy_key, __this__rolePrivileges_copy_value);
            }
            this.rolePrivileges = __this__rolePrivileges;
        }
    }

    @Override
    public PrincipalPrivilegeSet deepCopy() {
        return new PrincipalPrivilegeSet(this);
    }

    @Override
    public void clear() {
        this.userPrivileges = null;
        this.groupPrivileges = null;
        this.rolePrivileges = null;
    }

    public int getUserPrivilegesSize() {
        return (this.userPrivileges == null) ? 0 : this.userPrivileges.size();
    }

    public void putToUserPrivileges(java.lang.String key, java.util.List<PrivilegeGrantInfo> val) {
        if (this.userPrivileges == null) {
            this.userPrivileges = new java.util.HashMap<java.lang.String, java.util.List<PrivilegeGrantInfo>>();
        }
        this.userPrivileges.put(key, val);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> getUserPrivileges() {
        return this.userPrivileges;
    }

    public PrincipalPrivilegeSet setUserPrivileges(
        @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> userPrivileges
    ) {
        this.userPrivileges = userPrivileges;
        return this;
    }

    public void unsetUserPrivileges() {
        this.userPrivileges = null;
    }

    /** Returns true if field userPrivileges is set (has been assigned a value) and false otherwise */
    public boolean isSetUserPrivileges() {
        return this.userPrivileges != null;
    }

    public void setUserPrivilegesIsSet(boolean value) {
        if (!value) {
            this.userPrivileges = null;
        }
    }

    public int getGroupPrivilegesSize() {
        return (this.groupPrivileges == null) ? 0 : this.groupPrivileges.size();
    }

    public void putToGroupPrivileges(java.lang.String key, java.util.List<PrivilegeGrantInfo> val) {
        if (this.groupPrivileges == null) {
            this.groupPrivileges = new java.util.HashMap<java.lang.String, java.util.List<PrivilegeGrantInfo>>();
        }
        this.groupPrivileges.put(key, val);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> getGroupPrivileges() {
        return this.groupPrivileges;
    }

    public PrincipalPrivilegeSet setGroupPrivileges(
        @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> groupPrivileges
    ) {
        this.groupPrivileges = groupPrivileges;
        return this;
    }

    public void unsetGroupPrivileges() {
        this.groupPrivileges = null;
    }

    /** Returns true if field groupPrivileges is set (has been assigned a value) and false otherwise */
    public boolean isSetGroupPrivileges() {
        return this.groupPrivileges != null;
    }

    public void setGroupPrivilegesIsSet(boolean value) {
        if (!value) {
            this.groupPrivileges = null;
        }
    }

    public int getRolePrivilegesSize() {
        return (this.rolePrivileges == null) ? 0 : this.rolePrivileges.size();
    }

    public void putToRolePrivileges(java.lang.String key, java.util.List<PrivilegeGrantInfo> val) {
        if (this.rolePrivileges == null) {
            this.rolePrivileges = new java.util.HashMap<java.lang.String, java.util.List<PrivilegeGrantInfo>>();
        }
        this.rolePrivileges.put(key, val);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> getRolePrivileges() {
        return this.rolePrivileges;
    }

    public PrincipalPrivilegeSet setRolePrivileges(
        @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>> rolePrivileges
    ) {
        this.rolePrivileges = rolePrivileges;
        return this;
    }

    public void unsetRolePrivileges() {
        this.rolePrivileges = null;
    }

    /** Returns true if field rolePrivileges is set (has been assigned a value) and false otherwise */
    public boolean isSetRolePrivileges() {
        return this.rolePrivileges != null;
    }

    public void setRolePrivilegesIsSet(boolean value) {
        if (!value) {
            this.rolePrivileges = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case USER_PRIVILEGES:
                if (value == null) {
                    unsetUserPrivileges();
                } else {
                    setUserPrivileges((java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>>) value);
                }
                break;

            case GROUP_PRIVILEGES:
                if (value == null) {
                    unsetGroupPrivileges();
                } else {
                    setGroupPrivileges((java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>>) value);
                }
                break;

            case ROLE_PRIVILEGES:
                if (value == null) {
                    unsetRolePrivileges();
                } else {
                    setRolePrivileges((java.util.Map<java.lang.String, java.util.List<PrivilegeGrantInfo>>) value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case USER_PRIVILEGES:
                return getUserPrivileges();

            case GROUP_PRIVILEGES:
                return getGroupPrivileges();

            case ROLE_PRIVILEGES:
                return getRolePrivileges();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case USER_PRIVILEGES:
                return isSetUserPrivileges();
            case GROUP_PRIVILEGES:
                return isSetGroupPrivileges();
            case ROLE_PRIVILEGES:
                return isSetRolePrivileges();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that instanceof PrincipalPrivilegeSet) return this.equals((PrincipalPrivilegeSet) that);
        return false;
    }

    public boolean equals(PrincipalPrivilegeSet that) {
        if (that == null) return false;
        if (this == that) return true;

        boolean this_present_userPrivileges = true && this.isSetUserPrivileges();
        boolean that_present_userPrivileges = true && that.isSetUserPrivileges();
        if (this_present_userPrivileges || that_present_userPrivileges) {
            if (!(this_present_userPrivileges && that_present_userPrivileges)) return false;
            if (!this.userPrivileges.equals(that.userPrivileges)) return false;
        }

        boolean this_present_groupPrivileges = true && this.isSetGroupPrivileges();
        boolean that_present_groupPrivileges = true && that.isSetGroupPrivileges();
        if (this_present_groupPrivileges || that_present_groupPrivileges) {
            if (!(this_present_groupPrivileges && that_present_groupPrivileges)) return false;
            if (!this.groupPrivileges.equals(that.groupPrivileges)) return false;
        }

        boolean this_present_rolePrivileges = true && this.isSetRolePrivileges();
        boolean that_present_rolePrivileges = true && that.isSetRolePrivileges();
        if (this_present_rolePrivileges || that_present_rolePrivileges) {
            if (!(this_present_rolePrivileges && that_present_rolePrivileges)) return false;
            if (!this.rolePrivileges.equals(that.rolePrivileges)) return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetUserPrivileges()) ? 131071 : 524287);
        if (isSetUserPrivileges()) hashCode = hashCode * 8191 + userPrivileges.hashCode();

        hashCode = hashCode * 8191 + ((isSetGroupPrivileges()) ? 131071 : 524287);
        if (isSetGroupPrivileges()) hashCode = hashCode * 8191 + groupPrivileges.hashCode();

        hashCode = hashCode * 8191 + ((isSetRolePrivileges()) ? 131071 : 524287);
        if (isSetRolePrivileges()) hashCode = hashCode * 8191 + rolePrivileges.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(PrincipalPrivilegeSet other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.compare(isSetUserPrivileges(), other.isSetUserPrivileges());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetUserPrivileges()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userPrivileges, other.userPrivileges);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetGroupPrivileges(), other.isSetGroupPrivileges());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetGroupPrivileges()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.groupPrivileges, other.groupPrivileges);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetRolePrivileges(), other.isSetRolePrivileges());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetRolePrivileges()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rolePrivileges, other.rolePrivileges);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("PrincipalPrivilegeSet(");
        boolean first = true;

        sb.append("userPrivileges:");
        if (this.userPrivileges == null) {
            sb.append("null");
        } else {
            sb.append(this.userPrivileges);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("groupPrivileges:");
        if (this.groupPrivileges == null) {
            sb.append("null");
        } else {
            sb.append(this.groupPrivileges);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("rolePrivileges:");
        if (this.rolePrivileges == null) {
            sb.append("null");
        } else {
            sb.append(this.rolePrivileges);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class PrincipalPrivilegeSetStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public PrincipalPrivilegeSetStandardScheme getScheme() {
            return new PrincipalPrivilegeSetStandardScheme();
        }
    }

    private static class PrincipalPrivilegeSetStandardScheme extends org.apache.thrift.scheme.StandardScheme<PrincipalPrivilegeSet> {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, PrincipalPrivilegeSet struct) throws org.apache.thrift.TException {
            iprot.incrementRecursionDepth();
            try {
                org.apache.thrift.protocol.TField schemeField;
                iprot.readStructBegin();
                while (true) {
                    schemeField = iprot.readFieldBegin();
                    if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                        break;
                    }
                    switch (schemeField.id) {
                        case 1: // USER_PRIVILEGES
                            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                                {
                                    org.apache.thrift.protocol.TMap _map44 = iprot.readMapBegin();
                                    struct.userPrivileges = new java.util.HashMap<java.lang.String, java.util.List<PrivilegeGrantInfo>>(
                                        2 * _map44.size
                                    );
                                    @org.apache.thrift.annotation.Nullable
                                    java.lang.String _key45;
                                    @org.apache.thrift.annotation.Nullable
                                    java.util.List<PrivilegeGrantInfo> _val46;
                                    for (int _i47 = 0; _i47 < _map44.size; ++_i47) {
                                        _key45 = iprot.readString();
                                        {
                                            org.apache.thrift.protocol.TList _list48 = iprot.readListBegin();
                                            _val46 = new java.util.ArrayList<PrivilegeGrantInfo>(_list48.size);
                                            @org.apache.thrift.annotation.Nullable
                                            PrivilegeGrantInfo _elem49;
                                            for (int _i50 = 0; _i50 < _list48.size; ++_i50) {
                                                _elem49 = new PrivilegeGrantInfo();
                                                _elem49.read(iprot);
                                                _val46.add(_elem49);
                                            }
                                            iprot.readListEnd();
                                        }
                                        struct.userPrivileges.put(_key45, _val46);
                                    }
                                    iprot.readMapEnd();
                                }
                                struct.setUserPrivilegesIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        case 2: // GROUP_PRIVILEGES
                            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                                {
                                    org.apache.thrift.protocol.TMap _map51 = iprot.readMapBegin();
                                    struct.groupPrivileges = new java.util.HashMap<java.lang.String, java.util.List<PrivilegeGrantInfo>>(
                                        2 * _map51.size
                                    );
                                    @org.apache.thrift.annotation.Nullable
                                    java.lang.String _key52;
                                    @org.apache.thrift.annotation.Nullable
                                    java.util.List<PrivilegeGrantInfo> _val53;
                                    for (int _i54 = 0; _i54 < _map51.size; ++_i54) {
                                        _key52 = iprot.readString();
                                        {
                                            org.apache.thrift.protocol.TList _list55 = iprot.readListBegin();
                                            _val53 = new java.util.ArrayList<PrivilegeGrantInfo>(_list55.size);
                                            @org.apache.thrift.annotation.Nullable
                                            PrivilegeGrantInfo _elem56;
                                            for (int _i57 = 0; _i57 < _list55.size; ++_i57) {
                                                _elem56 = new PrivilegeGrantInfo();
                                                _elem56.read(iprot);
                                                _val53.add(_elem56);
                                            }
                                            iprot.readListEnd();
                                        }
                                        struct.groupPrivileges.put(_key52, _val53);
                                    }
                                    iprot.readMapEnd();
                                }
                                struct.setGroupPrivilegesIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        case 3: // ROLE_PRIVILEGES
                            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                                {
                                    org.apache.thrift.protocol.TMap _map58 = iprot.readMapBegin();
                                    struct.rolePrivileges = new java.util.HashMap<java.lang.String, java.util.List<PrivilegeGrantInfo>>(
                                        2 * _map58.size
                                    );
                                    @org.apache.thrift.annotation.Nullable
                                    java.lang.String _key59;
                                    @org.apache.thrift.annotation.Nullable
                                    java.util.List<PrivilegeGrantInfo> _val60;
                                    for (int _i61 = 0; _i61 < _map58.size; ++_i61) {
                                        _key59 = iprot.readString();
                                        {
                                            org.apache.thrift.protocol.TList _list62 = iprot.readListBegin();
                                            _val60 = new java.util.ArrayList<PrivilegeGrantInfo>(_list62.size);
                                            @org.apache.thrift.annotation.Nullable
                                            PrivilegeGrantInfo _elem63;
                                            for (int _i64 = 0; _i64 < _list62.size; ++_i64) {
                                                _elem63 = new PrivilegeGrantInfo();
                                                _elem63.read(iprot);
                                                _val60.add(_elem63);
                                            }
                                            iprot.readListEnd();
                                        }
                                        struct.rolePrivileges.put(_key59, _val60);
                                    }
                                    iprot.readMapEnd();
                                }
                                struct.setRolePrivilegesIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        default:
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                    }
                    iprot.readFieldEnd();
                }
                iprot.readStructEnd();

                // check for required fields of primitive type, which can't be checked in the validate method
                struct.validate();
            } finally {
                iprot.decrementRecursionDepth();
            }
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, PrincipalPrivilegeSet struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.userPrivileges != null) {
                oprot.writeFieldBegin(USER_PRIVILEGES_FIELD_DESC);
                {
                    oprot.writeMapBegin(
                        new org.apache.thrift.protocol.TMap(
                            org.apache.thrift.protocol.TType.STRING,
                            org.apache.thrift.protocol.TType.LIST,
                            struct.userPrivileges.size()
                        )
                    );
                    for (java.util.Map.Entry<java.lang.String, java.util.List<PrivilegeGrantInfo>> _iter65 : struct.userPrivileges
                        .entrySet()) {
                        oprot.writeString(_iter65.getKey());
                        {
                            oprot.writeListBegin(
                                new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, _iter65.getValue().size())
                            );
                            for (PrivilegeGrantInfo _iter66 : _iter65.getValue()) {
                                _iter66.write(oprot);
                            }
                            oprot.writeListEnd();
                        }
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.groupPrivileges != null) {
                oprot.writeFieldBegin(GROUP_PRIVILEGES_FIELD_DESC);
                {
                    oprot.writeMapBegin(
                        new org.apache.thrift.protocol.TMap(
                            org.apache.thrift.protocol.TType.STRING,
                            org.apache.thrift.protocol.TType.LIST,
                            struct.groupPrivileges.size()
                        )
                    );
                    for (java.util.Map.Entry<java.lang.String, java.util.List<PrivilegeGrantInfo>> _iter67 : struct.groupPrivileges
                        .entrySet()) {
                        oprot.writeString(_iter67.getKey());
                        {
                            oprot.writeListBegin(
                                new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, _iter67.getValue().size())
                            );
                            for (PrivilegeGrantInfo _iter68 : _iter67.getValue()) {
                                _iter68.write(oprot);
                            }
                            oprot.writeListEnd();
                        }
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.rolePrivileges != null) {
                oprot.writeFieldBegin(ROLE_PRIVILEGES_FIELD_DESC);
                {
                    oprot.writeMapBegin(
                        new org.apache.thrift.protocol.TMap(
                            org.apache.thrift.protocol.TType.STRING,
                            org.apache.thrift.protocol.TType.LIST,
                            struct.rolePrivileges.size()
                        )
                    );
                    for (java.util.Map.Entry<java.lang.String, java.util.List<PrivilegeGrantInfo>> _iter69 : struct.rolePrivileges
                        .entrySet()) {
                        oprot.writeString(_iter69.getKey());
                        {
                            oprot.writeListBegin(
                                new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, _iter69.getValue().size())
                            );
                            for (PrivilegeGrantInfo _iter70 : _iter69.getValue()) {
                                _iter70.write(oprot);
                            }
                            oprot.writeListEnd();
                        }
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class PrincipalPrivilegeSetTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public PrincipalPrivilegeSetTupleScheme getScheme() {
            return new PrincipalPrivilegeSetTupleScheme();
        }
    }

    private static class PrincipalPrivilegeSetTupleScheme extends org.apache.thrift.scheme.TupleScheme<PrincipalPrivilegeSet> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, PrincipalPrivilegeSet struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetUserPrivileges()) {
                optionals.set(0);
            }
            if (struct.isSetGroupPrivileges()) {
                optionals.set(1);
            }
            if (struct.isSetRolePrivileges()) {
                optionals.set(2);
            }
            oprot.writeBitSet(optionals, 3);
            if (struct.isSetUserPrivileges()) {
                {
                    oprot.writeI32(struct.userPrivileges.size());
                    for (java.util.Map.Entry<java.lang.String, java.util.List<PrivilegeGrantInfo>> _iter71 : struct.userPrivileges
                        .entrySet()) {
                        oprot.writeString(_iter71.getKey());
                        {
                            oprot.writeI32(_iter71.getValue().size());
                            for (PrivilegeGrantInfo _iter72 : _iter71.getValue()) {
                                _iter72.write(oprot);
                            }
                        }
                    }
                }
            }
            if (struct.isSetGroupPrivileges()) {
                {
                    oprot.writeI32(struct.groupPrivileges.size());
                    for (java.util.Map.Entry<java.lang.String, java.util.List<PrivilegeGrantInfo>> _iter73 : struct.groupPrivileges
                        .entrySet()) {
                        oprot.writeString(_iter73.getKey());
                        {
                            oprot.writeI32(_iter73.getValue().size());
                            for (PrivilegeGrantInfo _iter74 : _iter73.getValue()) {
                                _iter74.write(oprot);
                            }
                        }
                    }
                }
            }
            if (struct.isSetRolePrivileges()) {
                {
                    oprot.writeI32(struct.rolePrivileges.size());
                    for (java.util.Map.Entry<java.lang.String, java.util.List<PrivilegeGrantInfo>> _iter75 : struct.rolePrivileges
                        .entrySet()) {
                        oprot.writeString(_iter75.getKey());
                        {
                            oprot.writeI32(_iter75.getValue().size());
                            for (PrivilegeGrantInfo _iter76 : _iter75.getValue()) {
                                _iter76.write(oprot);
                            }
                        }
                    }
                }
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, PrincipalPrivilegeSet struct) throws org.apache.thrift.TException {
            prot.incrementRecursionDepth();
            try {
                org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
                java.util.BitSet incoming = iprot.readBitSet(3);
                if (incoming.get(0)) {
                    {
                        org.apache.thrift.protocol.TMap _map77 = iprot.readMapBegin(
                            org.apache.thrift.protocol.TType.STRING,
                            org.apache.thrift.protocol.TType.LIST
                        );
                        struct.userPrivileges = new java.util.HashMap<java.lang.String, java.util.List<PrivilegeGrantInfo>>(
                            2 * _map77.size
                        );
                        @org.apache.thrift.annotation.Nullable
                        java.lang.String _key78;
                        @org.apache.thrift.annotation.Nullable
                        java.util.List<PrivilegeGrantInfo> _val79;
                        for (int _i80 = 0; _i80 < _map77.size; ++_i80) {
                            _key78 = iprot.readString();
                            {
                                org.apache.thrift.protocol.TList _list81 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
                                _val79 = new java.util.ArrayList<PrivilegeGrantInfo>(_list81.size);
                                @org.apache.thrift.annotation.Nullable
                                PrivilegeGrantInfo _elem82;
                                for (int _i83 = 0; _i83 < _list81.size; ++_i83) {
                                    _elem82 = new PrivilegeGrantInfo();
                                    _elem82.read(iprot);
                                    _val79.add(_elem82);
                                }
                            }
                            struct.userPrivileges.put(_key78, _val79);
                        }
                    }
                    struct.setUserPrivilegesIsSet(true);
                }
                if (incoming.get(1)) {
                    {
                        org.apache.thrift.protocol.TMap _map84 = iprot.readMapBegin(
                            org.apache.thrift.protocol.TType.STRING,
                            org.apache.thrift.protocol.TType.LIST
                        );
                        struct.groupPrivileges = new java.util.HashMap<java.lang.String, java.util.List<PrivilegeGrantInfo>>(
                            2 * _map84.size
                        );
                        @org.apache.thrift.annotation.Nullable
                        java.lang.String _key85;
                        @org.apache.thrift.annotation.Nullable
                        java.util.List<PrivilegeGrantInfo> _val86;
                        for (int _i87 = 0; _i87 < _map84.size; ++_i87) {
                            _key85 = iprot.readString();
                            {
                                org.apache.thrift.protocol.TList _list88 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
                                _val86 = new java.util.ArrayList<PrivilegeGrantInfo>(_list88.size);
                                @org.apache.thrift.annotation.Nullable
                                PrivilegeGrantInfo _elem89;
                                for (int _i90 = 0; _i90 < _list88.size; ++_i90) {
                                    _elem89 = new PrivilegeGrantInfo();
                                    _elem89.read(iprot);
                                    _val86.add(_elem89);
                                }
                            }
                            struct.groupPrivileges.put(_key85, _val86);
                        }
                    }
                    struct.setGroupPrivilegesIsSet(true);
                }
                if (incoming.get(2)) {
                    {
                        org.apache.thrift.protocol.TMap _map91 = iprot.readMapBegin(
                            org.apache.thrift.protocol.TType.STRING,
                            org.apache.thrift.protocol.TType.LIST
                        );
                        struct.rolePrivileges = new java.util.HashMap<java.lang.String, java.util.List<PrivilegeGrantInfo>>(
                            2 * _map91.size
                        );
                        @org.apache.thrift.annotation.Nullable
                        java.lang.String _key92;
                        @org.apache.thrift.annotation.Nullable
                        java.util.List<PrivilegeGrantInfo> _val93;
                        for (int _i94 = 0; _i94 < _map91.size; ++_i94) {
                            _key92 = iprot.readString();
                            {
                                org.apache.thrift.protocol.TList _list95 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
                                _val93 = new java.util.ArrayList<PrivilegeGrantInfo>(_list95.size);
                                @org.apache.thrift.annotation.Nullable
                                PrivilegeGrantInfo _elem96;
                                for (int _i97 = 0; _i97 < _list95.size; ++_i97) {
                                    _elem96 = new PrivilegeGrantInfo();
                                    _elem96.read(iprot);
                                    _val93.add(_elem96);
                                }
                            }
                            struct.rolePrivileges.put(_key92, _val93);
                        }
                    }
                    struct.setRolePrivilegesIsSet(true);
                }
            } finally {
                prot.decrementRecursionDepth();
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY)
            .getScheme();
    }
}
