/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.opensearch.plugin.hive.metastore;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked", "unused" })
public class Table implements org.apache.thrift.TBase<Table, Table._Fields>, java.io.Serializable, Cloneable, Comparable<Table> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Table");

    private static final org.apache.thrift.protocol.TField TABLE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "tableName",
        org.apache.thrift.protocol.TType.STRING,
        (short) 1
    );
    private static final org.apache.thrift.protocol.TField DB_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "dbName",
        org.apache.thrift.protocol.TType.STRING,
        (short) 2
    );
    private static final org.apache.thrift.protocol.TField OWNER_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "owner",
        org.apache.thrift.protocol.TType.STRING,
        (short) 3
    );
    private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "createTime",
        org.apache.thrift.protocol.TType.I32,
        (short) 4
    );
    private static final org.apache.thrift.protocol.TField LAST_ACCESS_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "lastAccessTime",
        org.apache.thrift.protocol.TType.I32,
        (short) 5
    );
    private static final org.apache.thrift.protocol.TField RETENTION_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "retention",
        org.apache.thrift.protocol.TType.I32,
        (short) 6
    );
    private static final org.apache.thrift.protocol.TField SD_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "sd",
        org.apache.thrift.protocol.TType.STRUCT,
        (short) 7
    );
    private static final org.apache.thrift.protocol.TField PARTITION_KEYS_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "partitionKeys",
        org.apache.thrift.protocol.TType.LIST,
        (short) 8
    );
    private static final org.apache.thrift.protocol.TField PARAMETERS_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "parameters",
        org.apache.thrift.protocol.TType.MAP,
        (short) 9
    );
    private static final org.apache.thrift.protocol.TField VIEW_ORIGINAL_TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "viewOriginalText",
        org.apache.thrift.protocol.TType.STRING,
        (short) 10
    );
    private static final org.apache.thrift.protocol.TField VIEW_EXPANDED_TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "viewExpandedText",
        org.apache.thrift.protocol.TType.STRING,
        (short) 11
    );
    private static final org.apache.thrift.protocol.TField TABLE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField(
        "tableType",
        org.apache.thrift.protocol.TType.STRING,
        (short) 12
    );

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TableStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TableTupleSchemeFactory();

    private @org.apache.thrift.annotation.Nullable java.lang.String tableName; // required
    private @org.apache.thrift.annotation.Nullable java.lang.String dbName; // required
    private @org.apache.thrift.annotation.Nullable java.lang.String owner; // required
    private int createTime; // required
    private int lastAccessTime; // required
    private int retention; // required
    private @org.apache.thrift.annotation.Nullable StorageDescriptor sd; // required
    private @org.apache.thrift.annotation.Nullable java.util.List<FieldSchema> partitionKeys; // required
    private @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.lang.String> parameters; // required
    private @org.apache.thrift.annotation.Nullable java.lang.String viewOriginalText; // required
    private @org.apache.thrift.annotation.Nullable java.lang.String viewExpandedText; // required
    private @org.apache.thrift.annotation.Nullable java.lang.String tableType; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        TABLE_NAME((short) 1, "tableName"),
        DB_NAME((short) 2, "dbName"),
        OWNER((short) 3, "owner"),
        CREATE_TIME((short) 4, "createTime"),
        LAST_ACCESS_TIME((short) 5, "lastAccessTime"),
        RETENTION((short) 6, "retention"),
        SD((short) 7, "sd"),
        PARTITION_KEYS((short) 8, "partitionKeys"),
        PARAMETERS((short) 9, "parameters"),
        VIEW_ORIGINAL_TEXT((short) 10, "viewOriginalText"),
        VIEW_EXPANDED_TEXT((short) 11, "viewExpandedText"),
        TABLE_TYPE((short) 12, "tableType");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // TABLE_NAME
                    return TABLE_NAME;
                case 2: // DB_NAME
                    return DB_NAME;
                case 3: // OWNER
                    return OWNER;
                case 4: // CREATE_TIME
                    return CREATE_TIME;
                case 5: // LAST_ACCESS_TIME
                    return LAST_ACCESS_TIME;
                case 6: // RETENTION
                    return RETENTION;
                case 7: // SD
                    return SD;
                case 8: // PARTITION_KEYS
                    return PARTITION_KEYS;
                case 9: // PARAMETERS
                    return PARAMETERS;
                case 10: // VIEW_ORIGINAL_TEXT
                    return VIEW_ORIGINAL_TEXT;
                case 11: // VIEW_EXPANDED_TEXT
                    return VIEW_EXPANDED_TEXT;
                case 12: // TABLE_TYPE
                    return TABLE_TYPE;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId() {
            return _thriftId;
        }

        @Override
        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __CREATETIME_ISSET_ID = 0;
    private static final int __LASTACCESSTIME_ISSET_ID = 1;
    private static final int __RETENTION_ISSET_ID = 2;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<
            _Fields,
            org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(
            _Fields.TABLE_NAME,
            new org.apache.thrift.meta_data.FieldMetaData(
                "tableName",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)
            )
        );
        tmpMap.put(
            _Fields.DB_NAME,
            new org.apache.thrift.meta_data.FieldMetaData(
                "dbName",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)
            )
        );
        tmpMap.put(
            _Fields.OWNER,
            new org.apache.thrift.meta_data.FieldMetaData(
                "owner",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)
            )
        );
        tmpMap.put(
            _Fields.CREATE_TIME,
            new org.apache.thrift.meta_data.FieldMetaData(
                "createTime",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)
            )
        );
        tmpMap.put(
            _Fields.LAST_ACCESS_TIME,
            new org.apache.thrift.meta_data.FieldMetaData(
                "lastAccessTime",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)
            )
        );
        tmpMap.put(
            _Fields.RETENTION,
            new org.apache.thrift.meta_data.FieldMetaData(
                "retention",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)
            )
        );
        tmpMap.put(
            _Fields.SD,
            new org.apache.thrift.meta_data.FieldMetaData(
                "sd",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, StorageDescriptor.class)
            )
        );
        tmpMap.put(
            _Fields.PARTITION_KEYS,
            new org.apache.thrift.meta_data.FieldMetaData(
                "partitionKeys",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.ListMetaData(
                    org.apache.thrift.protocol.TType.LIST,
                    new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, FieldSchema.class)
                )
            )
        );
        tmpMap.put(
            _Fields.PARAMETERS,
            new org.apache.thrift.meta_data.FieldMetaData(
                "parameters",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.MapMetaData(
                    org.apache.thrift.protocol.TType.MAP,
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)
                )
            )
        );
        tmpMap.put(
            _Fields.VIEW_ORIGINAL_TEXT,
            new org.apache.thrift.meta_data.FieldMetaData(
                "viewOriginalText",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)
            )
        );
        tmpMap.put(
            _Fields.VIEW_EXPANDED_TEXT,
            new org.apache.thrift.meta_data.FieldMetaData(
                "viewExpandedText",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)
            )
        );
        tmpMap.put(
            _Fields.TABLE_TYPE,
            new org.apache.thrift.meta_data.FieldMetaData(
                "tableType",
                org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)
            )
        );
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Table.class, metaDataMap);
    }

    public Table() {}

    public Table(
        java.lang.String tableName,
        java.lang.String dbName,
        java.lang.String owner,
        int createTime,
        int lastAccessTime,
        int retention,
        StorageDescriptor sd,
        java.util.List<FieldSchema> partitionKeys,
        java.util.Map<java.lang.String, java.lang.String> parameters,
        java.lang.String viewOriginalText,
        java.lang.String viewExpandedText,
        java.lang.String tableType
    ) {
        this();
        this.tableName = tableName;
        this.dbName = dbName;
        this.owner = owner;
        this.createTime = createTime;
        setCreateTimeIsSet(true);
        this.lastAccessTime = lastAccessTime;
        setLastAccessTimeIsSet(true);
        this.retention = retention;
        setRetentionIsSet(true);
        this.sd = sd;
        this.partitionKeys = partitionKeys;
        this.parameters = parameters;
        this.viewOriginalText = viewOriginalText;
        this.viewExpandedText = viewExpandedText;
        this.tableType = tableType;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public Table(Table other) {
        __isset_bitfield = other.__isset_bitfield;
        if (other.isSetTableName()) {
            this.tableName = other.tableName;
        }
        if (other.isSetDbName()) {
            this.dbName = other.dbName;
        }
        if (other.isSetOwner()) {
            this.owner = other.owner;
        }
        this.createTime = other.createTime;
        this.lastAccessTime = other.lastAccessTime;
        this.retention = other.retention;
        if (other.isSetSd()) {
            this.sd = new StorageDescriptor(other.sd);
        }
        if (other.isSetPartitionKeys()) {
            java.util.List<FieldSchema> __this__partitionKeys = new java.util.ArrayList<FieldSchema>(other.partitionKeys.size());
            for (FieldSchema other_element : other.partitionKeys) {
                __this__partitionKeys.add(new FieldSchema(other_element));
            }
            this.partitionKeys = __this__partitionKeys;
        }
        if (other.isSetParameters()) {
            java.util.Map<java.lang.String, java.lang.String> __this__parameters = new java.util.TreeMap<
                java.lang.String,
                java.lang.String>(other.parameters);
            this.parameters = __this__parameters;
        }
        if (other.isSetViewOriginalText()) {
            this.viewOriginalText = other.viewOriginalText;
        }
        if (other.isSetViewExpandedText()) {
            this.viewExpandedText = other.viewExpandedText;
        }
        if (other.isSetTableType()) {
            this.tableType = other.tableType;
        }
    }

    @Override
    public Table deepCopy() {
        return new Table(this);
    }

    @Override
    public void clear() {
        this.tableName = null;
        this.dbName = null;
        this.owner = null;
        setCreateTimeIsSet(false);
        this.createTime = 0;
        setLastAccessTimeIsSet(false);
        this.lastAccessTime = 0;
        setRetentionIsSet(false);
        this.retention = 0;
        this.sd = null;
        this.partitionKeys = null;
        this.parameters = null;
        this.viewOriginalText = null;
        this.viewExpandedText = null;
        this.tableType = null;
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getTableName() {
        return this.tableName;
    }

    public Table setTableName(@org.apache.thrift.annotation.Nullable java.lang.String tableName) {
        this.tableName = tableName;
        return this;
    }

    public void unsetTableName() {
        this.tableName = null;
    }

    /** Returns true if field tableName is set (has been assigned a value) and false otherwise */
    public boolean isSetTableName() {
        return this.tableName != null;
    }

    public void setTableNameIsSet(boolean value) {
        if (!value) {
            this.tableName = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getDbName() {
        return this.dbName;
    }

    public Table setDbName(@org.apache.thrift.annotation.Nullable java.lang.String dbName) {
        this.dbName = dbName;
        return this;
    }

    public void unsetDbName() {
        this.dbName = null;
    }

    /** Returns true if field dbName is set (has been assigned a value) and false otherwise */
    public boolean isSetDbName() {
        return this.dbName != null;
    }

    public void setDbNameIsSet(boolean value) {
        if (!value) {
            this.dbName = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getOwner() {
        return this.owner;
    }

    public Table setOwner(@org.apache.thrift.annotation.Nullable java.lang.String owner) {
        this.owner = owner;
        return this;
    }

    public void unsetOwner() {
        this.owner = null;
    }

    /** Returns true if field owner is set (has been assigned a value) and false otherwise */
    public boolean isSetOwner() {
        return this.owner != null;
    }

    public void setOwnerIsSet(boolean value) {
        if (!value) {
            this.owner = null;
        }
    }

    public int getCreateTime() {
        return this.createTime;
    }

    public Table setCreateTime(int createTime) {
        this.createTime = createTime;
        setCreateTimeIsSet(true);
        return this;
    }

    public void unsetCreateTime() {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATETIME_ISSET_ID);
    }

    /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
    public boolean isSetCreateTime() {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATETIME_ISSET_ID);
    }

    public void setCreateTimeIsSet(boolean value) {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATETIME_ISSET_ID, value);
    }

    public int getLastAccessTime() {
        return this.lastAccessTime;
    }

    public Table setLastAccessTime(int lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
        setLastAccessTimeIsSet(true);
        return this;
    }

    public void unsetLastAccessTime() {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LASTACCESSTIME_ISSET_ID);
    }

    /** Returns true if field lastAccessTime is set (has been assigned a value) and false otherwise */
    public boolean isSetLastAccessTime() {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LASTACCESSTIME_ISSET_ID);
    }

    public void setLastAccessTimeIsSet(boolean value) {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LASTACCESSTIME_ISSET_ID, value);
    }

    public int getRetention() {
        return this.retention;
    }

    public Table setRetention(int retention) {
        this.retention = retention;
        setRetentionIsSet(true);
        return this;
    }

    public void unsetRetention() {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RETENTION_ISSET_ID);
    }

    /** Returns true if field retention is set (has been assigned a value) and false otherwise */
    public boolean isSetRetention() {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RETENTION_ISSET_ID);
    }

    public void setRetentionIsSet(boolean value) {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RETENTION_ISSET_ID, value);
    }

    @org.apache.thrift.annotation.Nullable
    public StorageDescriptor getSd() {
        return this.sd;
    }

    public Table setSd(@org.apache.thrift.annotation.Nullable StorageDescriptor sd) {
        this.sd = sd;
        return this;
    }

    public void unsetSd() {
        this.sd = null;
    }

    /** Returns true if field sd is set (has been assigned a value) and false otherwise */
    public boolean isSetSd() {
        return this.sd != null;
    }

    public void setSdIsSet(boolean value) {
        if (!value) {
            this.sd = null;
        }
    }

    public int getPartitionKeysSize() {
        return (this.partitionKeys == null) ? 0 : this.partitionKeys.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<FieldSchema> getPartitionKeysIterator() {
        return (this.partitionKeys == null) ? null : this.partitionKeys.iterator();
    }

    public void addToPartitionKeys(FieldSchema elem) {
        if (this.partitionKeys == null) {
            this.partitionKeys = new java.util.ArrayList<FieldSchema>();
        }
        this.partitionKeys.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.List<FieldSchema> getPartitionKeys() {
        return this.partitionKeys;
    }

    public Table setPartitionKeys(@org.apache.thrift.annotation.Nullable java.util.List<FieldSchema> partitionKeys) {
        this.partitionKeys = partitionKeys;
        return this;
    }

    public void unsetPartitionKeys() {
        this.partitionKeys = null;
    }

    /** Returns true if field partitionKeys is set (has been assigned a value) and false otherwise */
    public boolean isSetPartitionKeys() {
        return this.partitionKeys != null;
    }

    public void setPartitionKeysIsSet(boolean value) {
        if (!value) {
            this.partitionKeys = null;
        }
    }

    public int getParametersSize() {
        return (this.parameters == null) ? 0 : this.parameters.size();
    }

    public void putToParameters(java.lang.String key, java.lang.String val) {
        if (this.parameters == null) {
            this.parameters = new java.util.TreeMap<java.lang.String, java.lang.String>();
        }
        this.parameters.put(key, val);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Map<java.lang.String, java.lang.String> getParameters() {
        return this.parameters;
    }

    public Table setParameters(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.lang.String> parameters) {
        this.parameters = parameters;
        return this;
    }

    public void unsetParameters() {
        this.parameters = null;
    }

    /** Returns true if field parameters is set (has been assigned a value) and false otherwise */
    public boolean isSetParameters() {
        return this.parameters != null;
    }

    public void setParametersIsSet(boolean value) {
        if (!value) {
            this.parameters = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getViewOriginalText() {
        return this.viewOriginalText;
    }

    public Table setViewOriginalText(@org.apache.thrift.annotation.Nullable java.lang.String viewOriginalText) {
        this.viewOriginalText = viewOriginalText;
        return this;
    }

    public void unsetViewOriginalText() {
        this.viewOriginalText = null;
    }

    /** Returns true if field viewOriginalText is set (has been assigned a value) and false otherwise */
    public boolean isSetViewOriginalText() {
        return this.viewOriginalText != null;
    }

    public void setViewOriginalTextIsSet(boolean value) {
        if (!value) {
            this.viewOriginalText = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getViewExpandedText() {
        return this.viewExpandedText;
    }

    public Table setViewExpandedText(@org.apache.thrift.annotation.Nullable java.lang.String viewExpandedText) {
        this.viewExpandedText = viewExpandedText;
        return this;
    }

    public void unsetViewExpandedText() {
        this.viewExpandedText = null;
    }

    /** Returns true if field viewExpandedText is set (has been assigned a value) and false otherwise */
    public boolean isSetViewExpandedText() {
        return this.viewExpandedText != null;
    }

    public void setViewExpandedTextIsSet(boolean value) {
        if (!value) {
            this.viewExpandedText = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getTableType() {
        return this.tableType;
    }

    public Table setTableType(@org.apache.thrift.annotation.Nullable java.lang.String tableType) {
        this.tableType = tableType;
        return this;
    }

    public void unsetTableType() {
        this.tableType = null;
    }

    /** Returns true if field tableType is set (has been assigned a value) and false otherwise */
    public boolean isSetTableType() {
        return this.tableType != null;
    }

    public void setTableTypeIsSet(boolean value) {
        if (!value) {
            this.tableType = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case TABLE_NAME:
                if (value == null) {
                    unsetTableName();
                } else {
                    setTableName((java.lang.String) value);
                }
                break;

            case DB_NAME:
                if (value == null) {
                    unsetDbName();
                } else {
                    setDbName((java.lang.String) value);
                }
                break;

            case OWNER:
                if (value == null) {
                    unsetOwner();
                } else {
                    setOwner((java.lang.String) value);
                }
                break;

            case CREATE_TIME:
                if (value == null) {
                    unsetCreateTime();
                } else {
                    setCreateTime((java.lang.Integer) value);
                }
                break;

            case LAST_ACCESS_TIME:
                if (value == null) {
                    unsetLastAccessTime();
                } else {
                    setLastAccessTime((java.lang.Integer) value);
                }
                break;

            case RETENTION:
                if (value == null) {
                    unsetRetention();
                } else {
                    setRetention((java.lang.Integer) value);
                }
                break;

            case SD:
                if (value == null) {
                    unsetSd();
                } else {
                    setSd((StorageDescriptor) value);
                }
                break;

            case PARTITION_KEYS:
                if (value == null) {
                    unsetPartitionKeys();
                } else {
                    setPartitionKeys((java.util.List<FieldSchema>) value);
                }
                break;

            case PARAMETERS:
                if (value == null) {
                    unsetParameters();
                } else {
                    setParameters((java.util.Map<java.lang.String, java.lang.String>) value);
                }
                break;

            case VIEW_ORIGINAL_TEXT:
                if (value == null) {
                    unsetViewOriginalText();
                } else {
                    setViewOriginalText((java.lang.String) value);
                }
                break;

            case VIEW_EXPANDED_TEXT:
                if (value == null) {
                    unsetViewExpandedText();
                } else {
                    setViewExpandedText((java.lang.String) value);
                }
                break;

            case TABLE_TYPE:
                if (value == null) {
                    unsetTableType();
                } else {
                    setTableType((java.lang.String) value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case TABLE_NAME:
                return getTableName();

            case DB_NAME:
                return getDbName();

            case OWNER:
                return getOwner();

            case CREATE_TIME:
                return getCreateTime();

            case LAST_ACCESS_TIME:
                return getLastAccessTime();

            case RETENTION:
                return getRetention();

            case SD:
                return getSd();

            case PARTITION_KEYS:
                return getPartitionKeys();

            case PARAMETERS:
                return getParameters();

            case VIEW_ORIGINAL_TEXT:
                return getViewOriginalText();

            case VIEW_EXPANDED_TEXT:
                return getViewExpandedText();

            case TABLE_TYPE:
                return getTableType();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case TABLE_NAME:
                return isSetTableName();
            case DB_NAME:
                return isSetDbName();
            case OWNER:
                return isSetOwner();
            case CREATE_TIME:
                return isSetCreateTime();
            case LAST_ACCESS_TIME:
                return isSetLastAccessTime();
            case RETENTION:
                return isSetRetention();
            case SD:
                return isSetSd();
            case PARTITION_KEYS:
                return isSetPartitionKeys();
            case PARAMETERS:
                return isSetParameters();
            case VIEW_ORIGINAL_TEXT:
                return isSetViewOriginalText();
            case VIEW_EXPANDED_TEXT:
                return isSetViewExpandedText();
            case TABLE_TYPE:
                return isSetTableType();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that instanceof Table) return this.equals((Table) that);
        return false;
    }

    public boolean equals(Table that) {
        if (that == null) return false;
        if (this == that) return true;

        boolean this_present_tableName = true && this.isSetTableName();
        boolean that_present_tableName = true && that.isSetTableName();
        if (this_present_tableName || that_present_tableName) {
            if (!(this_present_tableName && that_present_tableName)) return false;
            if (!this.tableName.equals(that.tableName)) return false;
        }

        boolean this_present_dbName = true && this.isSetDbName();
        boolean that_present_dbName = true && that.isSetDbName();
        if (this_present_dbName || that_present_dbName) {
            if (!(this_present_dbName && that_present_dbName)) return false;
            if (!this.dbName.equals(that.dbName)) return false;
        }

        boolean this_present_owner = true && this.isSetOwner();
        boolean that_present_owner = true && that.isSetOwner();
        if (this_present_owner || that_present_owner) {
            if (!(this_present_owner && that_present_owner)) return false;
            if (!this.owner.equals(that.owner)) return false;
        }

        boolean this_present_createTime = true;
        boolean that_present_createTime = true;
        if (this_present_createTime || that_present_createTime) {
            if (!(this_present_createTime && that_present_createTime)) return false;
            if (this.createTime != that.createTime) return false;
        }

        boolean this_present_lastAccessTime = true;
        boolean that_present_lastAccessTime = true;
        if (this_present_lastAccessTime || that_present_lastAccessTime) {
            if (!(this_present_lastAccessTime && that_present_lastAccessTime)) return false;
            if (this.lastAccessTime != that.lastAccessTime) return false;
        }

        boolean this_present_retention = true;
        boolean that_present_retention = true;
        if (this_present_retention || that_present_retention) {
            if (!(this_present_retention && that_present_retention)) return false;
            if (this.retention != that.retention) return false;
        }

        boolean this_present_sd = true && this.isSetSd();
        boolean that_present_sd = true && that.isSetSd();
        if (this_present_sd || that_present_sd) {
            if (!(this_present_sd && that_present_sd)) return false;
            if (!this.sd.equals(that.sd)) return false;
        }

        boolean this_present_partitionKeys = true && this.isSetPartitionKeys();
        boolean that_present_partitionKeys = true && that.isSetPartitionKeys();
        if (this_present_partitionKeys || that_present_partitionKeys) {
            if (!(this_present_partitionKeys && that_present_partitionKeys)) return false;
            if (!this.partitionKeys.equals(that.partitionKeys)) return false;
        }

        boolean this_present_parameters = true && this.isSetParameters();
        boolean that_present_parameters = true && that.isSetParameters();
        if (this_present_parameters || that_present_parameters) {
            if (!(this_present_parameters && that_present_parameters)) return false;
            if (!this.parameters.equals(that.parameters)) return false;
        }

        boolean this_present_viewOriginalText = true && this.isSetViewOriginalText();
        boolean that_present_viewOriginalText = true && that.isSetViewOriginalText();
        if (this_present_viewOriginalText || that_present_viewOriginalText) {
            if (!(this_present_viewOriginalText && that_present_viewOriginalText)) return false;
            if (!this.viewOriginalText.equals(that.viewOriginalText)) return false;
        }

        boolean this_present_viewExpandedText = true && this.isSetViewExpandedText();
        boolean that_present_viewExpandedText = true && that.isSetViewExpandedText();
        if (this_present_viewExpandedText || that_present_viewExpandedText) {
            if (!(this_present_viewExpandedText && that_present_viewExpandedText)) return false;
            if (!this.viewExpandedText.equals(that.viewExpandedText)) return false;
        }

        boolean this_present_tableType = true && this.isSetTableType();
        boolean that_present_tableType = true && that.isSetTableType();
        if (this_present_tableType || that_present_tableType) {
            if (!(this_present_tableType && that_present_tableType)) return false;
            if (!this.tableType.equals(that.tableType)) return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetTableName()) ? 131071 : 524287);
        if (isSetTableName()) hashCode = hashCode * 8191 + tableName.hashCode();

        hashCode = hashCode * 8191 + ((isSetDbName()) ? 131071 : 524287);
        if (isSetDbName()) hashCode = hashCode * 8191 + dbName.hashCode();

        hashCode = hashCode * 8191 + ((isSetOwner()) ? 131071 : 524287);
        if (isSetOwner()) hashCode = hashCode * 8191 + owner.hashCode();

        hashCode = hashCode * 8191 + createTime;

        hashCode = hashCode * 8191 + lastAccessTime;

        hashCode = hashCode * 8191 + retention;

        hashCode = hashCode * 8191 + ((isSetSd()) ? 131071 : 524287);
        if (isSetSd()) hashCode = hashCode * 8191 + sd.hashCode();

        hashCode = hashCode * 8191 + ((isSetPartitionKeys()) ? 131071 : 524287);
        if (isSetPartitionKeys()) hashCode = hashCode * 8191 + partitionKeys.hashCode();

        hashCode = hashCode * 8191 + ((isSetParameters()) ? 131071 : 524287);
        if (isSetParameters()) hashCode = hashCode * 8191 + parameters.hashCode();

        hashCode = hashCode * 8191 + ((isSetViewOriginalText()) ? 131071 : 524287);
        if (isSetViewOriginalText()) hashCode = hashCode * 8191 + viewOriginalText.hashCode();

        hashCode = hashCode * 8191 + ((isSetViewExpandedText()) ? 131071 : 524287);
        if (isSetViewExpandedText()) hashCode = hashCode * 8191 + viewExpandedText.hashCode();

        hashCode = hashCode * 8191 + ((isSetTableType()) ? 131071 : 524287);
        if (isSetTableType()) hashCode = hashCode * 8191 + tableType.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(Table other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.compare(isSetTableName(), other.isSetTableName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTableName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tableName, other.tableName);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetDbName(), other.isSetDbName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetDbName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dbName, other.dbName);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetOwner(), other.isSetOwner());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetOwner()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.owner, other.owner);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetCreateTime(), other.isSetCreateTime());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetCreateTime()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetLastAccessTime(), other.isSetLastAccessTime());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetLastAccessTime()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastAccessTime, other.lastAccessTime);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetRetention(), other.isSetRetention());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetRetention()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.retention, other.retention);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetSd(), other.isSetSd());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetSd()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sd, other.sd);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetPartitionKeys(), other.isSetPartitionKeys());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetPartitionKeys()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.partitionKeys, other.partitionKeys);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetParameters(), other.isSetParameters());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetParameters()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.parameters, other.parameters);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetViewOriginalText(), other.isSetViewOriginalText());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetViewOriginalText()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.viewOriginalText, other.viewOriginalText);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetViewExpandedText(), other.isSetViewExpandedText());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetViewExpandedText()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.viewExpandedText, other.viewExpandedText);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetTableType(), other.isSetTableType());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTableType()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tableType, other.tableType);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("Table(");
        boolean first = true;

        sb.append("tableName:");
        if (this.tableName == null) {
            sb.append("null");
        } else {
            sb.append(this.tableName);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("dbName:");
        if (this.dbName == null) {
            sb.append("null");
        } else {
            sb.append(this.dbName);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("owner:");
        if (this.owner == null) {
            sb.append("null");
        } else {
            sb.append(this.owner);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("createTime:");
        sb.append(this.createTime);
        first = false;
        if (!first) sb.append(", ");
        sb.append("lastAccessTime:");
        sb.append(this.lastAccessTime);
        first = false;
        if (!first) sb.append(", ");
        sb.append("retention:");
        sb.append(this.retention);
        first = false;
        if (!first) sb.append(", ");
        sb.append("sd:");
        if (this.sd == null) {
            sb.append("null");
        } else {
            sb.append(this.sd);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("partitionKeys:");
        if (this.partitionKeys == null) {
            sb.append("null");
        } else {
            sb.append(this.partitionKeys);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("parameters:");
        if (this.parameters == null) {
            sb.append("null");
        } else {
            sb.append(this.parameters);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("viewOriginalText:");
        if (this.viewOriginalText == null) {
            sb.append("null");
        } else {
            sb.append(this.viewOriginalText);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("viewExpandedText:");
        if (this.viewExpandedText == null) {
            sb.append("null");
        } else {
            sb.append(this.viewExpandedText);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("tableType:");
        if (this.tableType == null) {
            sb.append("null");
        } else {
            sb.append(this.tableType);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
        if (sd != null) {
            sd.validate();
        }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class TableStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public TableStandardScheme getScheme() {
            return new TableStandardScheme();
        }
    }

    private static class TableStandardScheme extends org.apache.thrift.scheme.StandardScheme<Table> {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, Table struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // TABLE_NAME
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.tableName = iprot.readString();
                            struct.setTableNameIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // DB_NAME
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.dbName = iprot.readString();
                            struct.setDbNameIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // OWNER
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.owner = iprot.readString();
                            struct.setOwnerIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 4: // CREATE_TIME
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.createTime = iprot.readI32();
                            struct.setCreateTimeIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 5: // LAST_ACCESS_TIME
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.lastAccessTime = iprot.readI32();
                            struct.setLastAccessTimeIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 6: // RETENTION
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.retention = iprot.readI32();
                            struct.setRetentionIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 7: // SD
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.sd = new StorageDescriptor();
                            struct.sd.read(iprot);
                            struct.setSdIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 8: // PARTITION_KEYS
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list54 = iprot.readListBegin();
                                struct.partitionKeys = new java.util.ArrayList<FieldSchema>(_list54.size);
                                @org.apache.thrift.annotation.Nullable
                                FieldSchema _elem55;
                                for (int _i56 = 0; _i56 < _list54.size; ++_i56) {
                                    _elem55 = new FieldSchema();
                                    _elem55.read(iprot);
                                    struct.partitionKeys.add(_elem55);
                                }
                                iprot.readListEnd();
                            }
                            struct.setPartitionKeysIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 9: // PARAMETERS
                        if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                            {
                                org.apache.thrift.protocol.TMap _map57 = iprot.readMapBegin();
                                struct.parameters = new java.util.TreeMap<java.lang.String, java.lang.String>();
                                @org.apache.thrift.annotation.Nullable
                                java.lang.String _key58;
                                @org.apache.thrift.annotation.Nullable
                                java.lang.String _val59;
                                for (int _i60 = 0; _i60 < _map57.size; ++_i60) {
                                    _key58 = iprot.readString();
                                    _val59 = iprot.readString();
                                    struct.parameters.put(_key58, _val59);
                                }
                                iprot.readMapEnd();
                            }
                            struct.setParametersIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 10: // VIEW_ORIGINAL_TEXT
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.viewOriginalText = iprot.readString();
                            struct.setViewOriginalTextIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 11: // VIEW_EXPANDED_TEXT
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.viewExpandedText = iprot.readString();
                            struct.setViewExpandedTextIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 12: // TABLE_TYPE
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.tableType = iprot.readString();
                            struct.setTableTypeIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, Table struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.tableName != null) {
                oprot.writeFieldBegin(TABLE_NAME_FIELD_DESC);
                oprot.writeString(struct.tableName);
                oprot.writeFieldEnd();
            }
            if (struct.dbName != null) {
                oprot.writeFieldBegin(DB_NAME_FIELD_DESC);
                oprot.writeString(struct.dbName);
                oprot.writeFieldEnd();
            }
            if (struct.owner != null) {
                oprot.writeFieldBegin(OWNER_FIELD_DESC);
                oprot.writeString(struct.owner);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
            oprot.writeI32(struct.createTime);
            oprot.writeFieldEnd();
            oprot.writeFieldBegin(LAST_ACCESS_TIME_FIELD_DESC);
            oprot.writeI32(struct.lastAccessTime);
            oprot.writeFieldEnd();
            oprot.writeFieldBegin(RETENTION_FIELD_DESC);
            oprot.writeI32(struct.retention);
            oprot.writeFieldEnd();
            if (struct.sd != null) {
                oprot.writeFieldBegin(SD_FIELD_DESC);
                struct.sd.write(oprot);
                oprot.writeFieldEnd();
            }
            if (struct.partitionKeys != null) {
                oprot.writeFieldBegin(PARTITION_KEYS_FIELD_DESC);
                {
                    oprot.writeListBegin(
                        new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.partitionKeys.size())
                    );
                    for (FieldSchema _iter61 : struct.partitionKeys) {
                        _iter61.write(oprot);
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.parameters != null) {
                oprot.writeFieldBegin(PARAMETERS_FIELD_DESC);
                {
                    oprot.writeMapBegin(
                        new org.apache.thrift.protocol.TMap(
                            org.apache.thrift.protocol.TType.STRING,
                            org.apache.thrift.protocol.TType.STRING,
                            struct.parameters.size()
                        )
                    );
                    for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter62 : struct.parameters.entrySet()) {
                        oprot.writeString(_iter62.getKey());
                        oprot.writeString(_iter62.getValue());
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.viewOriginalText != null) {
                oprot.writeFieldBegin(VIEW_ORIGINAL_TEXT_FIELD_DESC);
                oprot.writeString(struct.viewOriginalText);
                oprot.writeFieldEnd();
            }
            if (struct.viewExpandedText != null) {
                oprot.writeFieldBegin(VIEW_EXPANDED_TEXT_FIELD_DESC);
                oprot.writeString(struct.viewExpandedText);
                oprot.writeFieldEnd();
            }
            if (struct.tableType != null) {
                oprot.writeFieldBegin(TABLE_TYPE_FIELD_DESC);
                oprot.writeString(struct.tableType);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class TableTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public TableTupleScheme getScheme() {
            return new TableTupleScheme();
        }
    }

    private static class TableTupleScheme extends org.apache.thrift.scheme.TupleScheme<Table> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, Table struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetTableName()) {
                optionals.set(0);
            }
            if (struct.isSetDbName()) {
                optionals.set(1);
            }
            if (struct.isSetOwner()) {
                optionals.set(2);
            }
            if (struct.isSetCreateTime()) {
                optionals.set(3);
            }
            if (struct.isSetLastAccessTime()) {
                optionals.set(4);
            }
            if (struct.isSetRetention()) {
                optionals.set(5);
            }
            if (struct.isSetSd()) {
                optionals.set(6);
            }
            if (struct.isSetPartitionKeys()) {
                optionals.set(7);
            }
            if (struct.isSetParameters()) {
                optionals.set(8);
            }
            if (struct.isSetViewOriginalText()) {
                optionals.set(9);
            }
            if (struct.isSetViewExpandedText()) {
                optionals.set(10);
            }
            if (struct.isSetTableType()) {
                optionals.set(11);
            }
            oprot.writeBitSet(optionals, 12);
            if (struct.isSetTableName()) {
                oprot.writeString(struct.tableName);
            }
            if (struct.isSetDbName()) {
                oprot.writeString(struct.dbName);
            }
            if (struct.isSetOwner()) {
                oprot.writeString(struct.owner);
            }
            if (struct.isSetCreateTime()) {
                oprot.writeI32(struct.createTime);
            }
            if (struct.isSetLastAccessTime()) {
                oprot.writeI32(struct.lastAccessTime);
            }
            if (struct.isSetRetention()) {
                oprot.writeI32(struct.retention);
            }
            if (struct.isSetSd()) {
                struct.sd.write(oprot);
            }
            if (struct.isSetPartitionKeys()) {
                {
                    oprot.writeI32(struct.partitionKeys.size());
                    for (FieldSchema _iter63 : struct.partitionKeys) {
                        _iter63.write(oprot);
                    }
                }
            }
            if (struct.isSetParameters()) {
                {
                    oprot.writeI32(struct.parameters.size());
                    for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter64 : struct.parameters.entrySet()) {
                        oprot.writeString(_iter64.getKey());
                        oprot.writeString(_iter64.getValue());
                    }
                }
            }
            if (struct.isSetViewOriginalText()) {
                oprot.writeString(struct.viewOriginalText);
            }
            if (struct.isSetViewExpandedText()) {
                oprot.writeString(struct.viewExpandedText);
            }
            if (struct.isSetTableType()) {
                oprot.writeString(struct.tableType);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, Table struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(12);
            if (incoming.get(0)) {
                struct.tableName = iprot.readString();
                struct.setTableNameIsSet(true);
            }
            if (incoming.get(1)) {
                struct.dbName = iprot.readString();
                struct.setDbNameIsSet(true);
            }
            if (incoming.get(2)) {
                struct.owner = iprot.readString();
                struct.setOwnerIsSet(true);
            }
            if (incoming.get(3)) {
                struct.createTime = iprot.readI32();
                struct.setCreateTimeIsSet(true);
            }
            if (incoming.get(4)) {
                struct.lastAccessTime = iprot.readI32();
                struct.setLastAccessTimeIsSet(true);
            }
            if (incoming.get(5)) {
                struct.retention = iprot.readI32();
                struct.setRetentionIsSet(true);
            }
            if (incoming.get(6)) {
                struct.sd = new StorageDescriptor();
                struct.sd.read(iprot);
                struct.setSdIsSet(true);
            }
            if (incoming.get(7)) {
                {
                    org.apache.thrift.protocol.TList _list65 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
                    struct.partitionKeys = new java.util.ArrayList<FieldSchema>(_list65.size);
                    @org.apache.thrift.annotation.Nullable
                    FieldSchema _elem66;
                    for (int _i67 = 0; _i67 < _list65.size; ++_i67) {
                        _elem66 = new FieldSchema();
                        _elem66.read(iprot);
                        struct.partitionKeys.add(_elem66);
                    }
                }
                struct.setPartitionKeysIsSet(true);
            }
            if (incoming.get(8)) {
                {
                    org.apache.thrift.protocol.TMap _map68 = iprot.readMapBegin(
                        org.apache.thrift.protocol.TType.STRING,
                        org.apache.thrift.protocol.TType.STRING
                    );
                    struct.parameters = new java.util.TreeMap<java.lang.String, java.lang.String>();
                    @org.apache.thrift.annotation.Nullable
                    java.lang.String _key69;
                    @org.apache.thrift.annotation.Nullable
                    java.lang.String _val70;
                    for (int _i71 = 0; _i71 < _map68.size; ++_i71) {
                        _key69 = iprot.readString();
                        _val70 = iprot.readString();
                        struct.parameters.put(_key69, _val70);
                    }
                }
                struct.setParametersIsSet(true);
            }
            if (incoming.get(9)) {
                struct.viewOriginalText = iprot.readString();
                struct.setViewOriginalTextIsSet(true);
            }
            if (incoming.get(10)) {
                struct.viewExpandedText = iprot.readString();
                struct.setViewExpandedTextIsSet(true);
            }
            if (incoming.get(11)) {
                struct.tableType = iprot.readString();
                struct.setTableTypeIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY)
            .getScheme();
    }
}
