[[breaking-changes]]
= Migration guide

[partintro]
--
This section describes the breaking changes and deprecations introduced in this release 
and previous minor versions. 

As {opensearch} introduces new features and improves existing ones, 
the changes sometimes make older settings, APIs, and parameters obsolete.
The obsolete functionality is typically deprecated in a minor release and 
removed in the subsequent major release.
This enables applications to continue working unchanged across most minor version upgrades.
Breaking changes introduced in minor releases are generally limited to critical security fixes 
and bug fixes that correct unintended behavior.

To get the most out of {opensearch} and facilitate future upgrades, we strongly encourage migrating
away from using deprecated functionality as soon as possible.

To give you insight into what deprecated features you're using, {opensearch}:

- Returns a `Warn` HTTP header whenever you submit a request that uses deprecated functionality.
- <<deprecation-logging, Logs deprecation warnings>> when deprecated functionality is used.

For more information about {minor-version}, 
see the <<release-highlights>> and <<opensearch-release-notes>>.
For information about how to upgrade your cluster, see <<setup-upgrade>>.

* <<breaking-changes-7.10,Migrating to 7.10>>

--

include::migrate_7_10.asciidoc[]
