name: (5.x) Check signed commits
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  # Checks if the commits are signed, if not the workflow will fail
  verify-signed-commits:
    if: ${{ !github.event.pull_request.draft && github.repository == 'wazuh/wazuh-indexer' }}
    runs-on:
      - codebuild-github-actions-codebuild-runner-indexer-amd-${{ github.run_id }}-${{ github.run_attempt }}
    permissions:
      contents: read
    steps:
      - uses: 1Password/check-signed-commits-action@v1
      
