name: (5.x) Check version file
permissions:
  contents: read

on:
  push:
    paths:
      - "VERSION.json"

jobs:
  check-version:
    runs-on:
      - codebuild-github-actions-codebuild-runner-indexer-amd-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v7

      - name: Check version
        run: bash build-scripts/check-version.sh
