name: Gradle Assemble
on:
  pull_request:
    # Skip this check unless files that could plausibly impact a
    # distribution have changed.
    paths:
      - 'distribution/**'
      - 'buildSrc/**'
      - '**/*.gradle'
      - 'gradle/**'
      - '.github/workflows/assemble.yml'

jobs:
  assemble:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 21, 25 ]
        os: [ubuntu-latest, windows-latest, macos-15, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v6
      - name: Install protoc (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          if [ "$(uname -m)" = "x86_64" ]; then \
              curl -SfL https://github.com/protocolbuffers/protobuf/releases/download/v33.0/protoc-33.0-linux-x86_64.zip -o protoc.zip; \
          else \
              curl -SfL https://github.com/protocolbuffers/protobuf/releases/download/v33.0/protoc-33.0-linux-aarch_64.zip -o protoc.zip; \
          fi; \
          unzip protoc.zip -d $HOME/.local && rm -v protoc.zip && protoc --version
      - name: Install protoc (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          scoop_update: false
          buckets: extras
          apps: protobuf
      - name: Install protoc (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: brew install protobuf
      # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
      - name: Remove unnecessary files Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Setup docker (missing on MacOS)
        id: setup_docker
        if: runner.os == 'macos'
        continue-on-error: true
        run: |
          brew install docker colima coreutils
          gtimeout 15m colima start
        shell: bash
      - name: Run Gradle (assemble)
        if: runner.os == 'macos' && steps.setup_docker.outcome != 'success'
        run: |
          # Report success even if previous step failed (Docker on MacOS runner is very unstable)
          exit 0;
      - name: Run Gradle (assemble)
        shell: bash
        if: runner.os != 'macos'
        run: |
          ./gradlew assemble --parallel --no-build-cache -PDISABLE_BUILD_CACHE
      - name: Run Gradle (assemble)
        if: runner.os == 'macos' && steps.setup_docker.outcome == 'success'
        run: |
          ./gradlew assemble --parallel --no-build-cache -PDISABLE_BUILD_CACHE
