name: Gradle Assemble
on: [pull_request]

jobs:
  assemble:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 21, 23 ]
        os: [ubuntu-latest, windows-latest, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
        # GitHub Actions still not supporting arm64 dind yet
        # https://github.com/douglascamata/setup-docker-macos-action?tab=readme-ov-file#arm64-processors-m-series-used-on-macos-14-images-and-beyond-are-unsupported
        # And they are deprecating the x64 macos-13 runner by 2025/11/14
        # https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/
        # All new macos-* are arm64 runner by default and x64 runner requires `larger` runner
        # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        # Only use non-arm64 agent in this workflow
      - name: Run Gradle (assemble)
        shell: bash
        run: |
          ./gradlew assemble --parallel --no-build-cache -PDISABLE_BUILD_CACHE 
