---
name: Backport
on:
  pull_request_target:
    types: [closed, labeled]

jobs:
  backport:
    if: github.repository == 'opensearch-project/OpenSearch'
    uses: opensearch-project/opensearch-build/.github/workflows/backport-pr.yml@58f2e5108a5164e37af78f5d8de5d825825023a9
    secrets:
      OPENSEARCH_CI_BOT_TOKEN: ${{ secrets.OPENSEARCH_CI_BOT_TOKEN }}
