name: Label Stalled PRs
on:
  schedule:
    - cron: '15 15 * * *' # Run every day at 15:15 UTC / 7:15 PST / 8:15 PDT
permissions:
  pull-requests: write
jobs:
  stale:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ubuntu-latest
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: opensearch-project
      - name: Stale PRs
        uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10
        with:
          repo-token: ${{ steps.github_app_token.outputs.token }}
          stale-pr-label: 'stalled'
          stale-pr-message: 'This PR is stalled because it has been open for 30 days with no activity.'
          days-before-pr-stale: 30
          days-before-issue-stale: -1
          days-before-pr-close: -1
          days-before-issue-close: -1
