name: Validate Gradle Wrapper
on: [pull_request]

jobs:
  validate:
    name: Validate
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: gradle/actions/wrapper-validation@0b6dd653ba04f4f93bf581ec31e66cbd7dcb644d # v4
